reXscript: parser Class Reference
parser Class Reference
#include <parser.hpp>
Public Member Functions
parser (lexer &lex)
AST parseBasicLiterals ()
AST parseIdentifier ()
AST parseSubscriptExpression ()
AST parseListLiteral ()
AST parseObjectLiteral ()
AST parseArguments ()
AST parseClosureDefinition ()
AST parseFunctionDefinition ()
AST parseMemberExpression ()
AST parsePrimary ()
AST parseUniqueExpression ()
AST parseMultiplicationExpression ()
AST parseAdditionExpression ()
AST parseBinaryShiftExpression ()
AST parseLogicEqualExpression ()
AST parseBinaryExpression ()
AST parseLogicAndExpression ()
AST parseLvalueExpression ()
AST parseAssignmentExpression ()
AST parseBlockStmt ()
AST parseLetStmt ()
AST parseWhileStmt ()
AST parseForStmt ()
AST parseRangeBasedForStmt ()
AST parseIfStmt ()
AST parseReturnStmt ()
AST parseContinueStmt ()
AST parseBreakStmt ()
AST parseTryCatchStmt ()
AST parseThrowStmt ()
AST parseFunctionDefStmt ()
AST parseWithStmt ()
AST parseStmts ()
AST parseFile ()
Static Public Member Functions
static AST makeNotMatch ()
Private Attributes
lexer & lex
Detailed Description
Definition at line 13 of file parser.hpp.
Constructor & Destructor Documentation
parser()
parser (lexer & lex)
Definition at line 9 of file parser.cpp.
References parser::lex, and lexer::scan().
Member Function Documentation
makeNotMatch()
AST makeNotMatch () static
Definition at line 42 of file parser.cpp.
References AST::notMatch.
Referenced by parser::parseAdditionExpression(), parser::parseArguments(), parser::parseAssignmentExpression(), parser::parseBasicLiterals(), parser::parseBinaryExpression(), parser::parseBinaryShiftExpression(), parser::parseBlockStmt(), parser::parseBreakStmt(), parser::parseClosureDefinition(), parser::parseContinueStmt(), parser::parseForStmt(), parser::parseFunctionDefinition(), parser::parseFunctionDefStmt(), parser::parseIdentifier(), parser::parseIfStmt(), parser::parseLetStmt(), parser::parseListLiteral(), parser::parseLogicAndExpression(), parser::parseLogicEqualExpression(), parser::parseMemberExpression(), parser::parseMultiplicationExpression(), parser::parseObjectLiteral(), parser::parsePrimary(), parser::parseRangeBasedForStmt(), parser::parseReturnStmt(), parser::parseSubscriptExpression(), parser::parseUniqueExpression(), parser::parseWhileStmt(), and parser::parseWithStmt().
parseAdditionExpression()
AST parseAdditionExpression ()
Definition at line 382 of file parser.cpp.
References AST::additionExpression, lexer::col, lexer::curToken, lexer::token::kind, parser::lex, lexer::line, parser::makeNotMatch(), lexer::token::minus, AST::operators, parser::parseMultiplicationExpression(), lexer::token::plus, and lexer::scan().
Referenced by parser::parseBinaryShiftExpression().
parseArguments()
AST parseArguments ()
Definition at line 151 of file parser.cpp.
References AST::arguments, AST::child, lexer::col, lexer::token::comma, lexer::curToken, lexer::token::kind, lexer::token::leftParentheses, parser::lex, lexer::line, parser::makeNotMatch(), parser::parseLvalueExpression(), lexer::token::rightParentheses, and lexer::scan().
Referenced by parser::parseSubscriptExpression().
parseAssignmentExpression()
AST parseAssignmentExpression ()
Definition at line 520 of file parser.cpp.
References lexer::token::additionAssignment, AST::assignmentExpression, lexer::token::assignSign, lexer::col, lexer::curToken, lexer::token::divisionAssignment, lexer::dropState(), lexer::token::kind, parser::lex, lexer::line, parser::makeNotMatch(), lexer::token::multiplicationAssignment, AST::operators, parser::parseLvalueExpression(), parser::parseMemberExpression(), lexer::token::reminderAssignment, lexer::returnState(), lexer::saveState(), lexer::scan(), and lexer::token::subtractionAssignment.
Referenced by parser::parseStmts().
parseBasicLiterals()
AST parseBasicLiterals ()
Definition at line 13 of file parser.cpp.
References AST::basicLiterals, lexer::token::boolean, lexer::curToken, lexer::token::decimal, lexer::token::integer, lexer::token::kind, lexer::token::kNull, parser::lex, parser::makeNotMatch(), lexer::scan(), and lexer::token::string.
Referenced by parser::parsePrimary().
parseBinaryExpression()
AST parseBinaryExpression ()
Definition at line 464 of file parser.cpp.
References lexer::token::binaryAnd, AST::binaryExpression, lexer::token::binaryOr, lexer::token::binaryXor, lexer::col, lexer::curToken, lexer::token::kind, parser::lex, lexer::line, parser::makeNotMatch(), AST::operators, parser::parseLogicEqualExpression(), and lexer::scan().
Referenced by parser::parseLogicAndExpression().
parseBinaryShiftExpression()
AST parseBinaryShiftExpression ()
Definition at line 406 of file parser.cpp.
References AST::binaryShiftExpression, lexer::token::binaryShiftLeft, lexer::token::binaryShiftRight, lexer::col, lexer::curToken, lexer::token::kind, parser::lex, lexer::line, parser::makeNotMatch(), AST::operators, parser::parseAdditionExpression(), and lexer::scan().
Referenced by parser::parseLogicEqualExpression().
parseBlockStmt()
AST parseBlockStmt ()
Definition at line 547 of file parser.cpp.
References AST::blockStmt, AST::child, lexer::col, lexer::curToken, AST::forStmt, AST::functionDefStmt, AST::ifElseStmt, AST::ifStmt, AST::kind, lexer::token::kind, lexer::token::leftBraces, parser::lex, lexer::line, parser::makeNotMatch(), parser::parseStmts(), AST::rangeBasedForStmt, lexer::token::rightBraces, lexer::scan(), lexer::token::semicolon, AST::whileStmt, and AST::withStmt.
Referenced by parser::parseClosureDefinition(), parser::parseFunctionDefinition(), parser::parseFunctionDefStmt(), parser::parseStmts(), and parser::parseTryCatchStmt().
parseBreakStmt()
AST parseBreakStmt ()
Definition at line 767 of file parser.cpp.
References AST::breakStmt, lexer::curToken, lexer::token::kBreak, lexer::token::kind, parser::lex, parser::makeNotMatch(), and lexer::scan().
Referenced by parser::parseStmts().
parseClosureDefinition()
AST parseClosureDefinition ()
Definition at line 173 of file parser.cpp.
References AST::arguments, AST::child, lexer::col, lexer::token::comma, lexer::curToken, lexer::token::kClosure, lexer::token::kind, AST::lambdaDefinition, lexer::token::leftParentheses, parser::lex, lexer::line, parser::makeNotMatch(), parser::parseBlockStmt(), parser::parseIdentifier(), lexer::token::rightParentheses, lexer::scan(), and lexer::token::toSign.
Referenced by parser::parsePrimary().
parseContinueStmt()
AST parseContinueStmt ()
Definition at line 758 of file parser.cpp.
References AST::continueStmt, lexer::curToken, lexer::token::kContinue, lexer::token::kind, parser::lex, parser::makeNotMatch(), and lexer::scan().
Referenced by parser::parseStmts().
parseFile()
AST parseFile ()
Definition at line 839 of file parser.cpp.
References AST::blockStmt, AST::child, lexer::col, lexer::curToken, AST::forStmt, AST::functionDefStmt, AST::ifElseStmt, AST::ifStmt, AST::kind, lexer::token::kind, parser::lex, lexer::line, parser::parseStmts(), AST::rangeBasedForStmt, lexer::scan(), lexer::token::semicolon, AST::whileStmt, and AST::withStmt.
Referenced by rex::getFileAST().
parseForStmt()
AST parseForStmt ()
Definition at line 639 of file parser.cpp.
References lexer::col, lexer::curToken, AST::forStmt, lexer::token::kFor, lexer::token::kind, lexer::token::leftParentheses, parser::lex, lexer::line, parser::makeNotMatch(), parser::parseLvalueExpression(), parser::parseStmts(), lexer::token::rightParentheses, lexer::scan(), and lexer::token::semicolon.
Referenced by parser::parseStmts().
parseFunctionDefinition()
AST parseFunctionDefinition ()
Definition at line 229 of file parser.cpp.
References AST::arguments, AST::child, lexer::col, lexer::token::comma, lexer::curToken, AST::functionDefinition, lexer::token::kFunc, lexer::token::kind, lexer::token::leftParentheses, parser::lex, lexer::line, parser::makeNotMatch(), parser::parseBlockStmt(), parser::parseIdentifier(), lexer::token::rightParentheses, and lexer::scan().
Referenced by parser::parsePrimary().
parseFunctionDefStmt()
AST parseFunctionDefStmt ()
Definition at line 900 of file parser.cpp.
References AST::arguments, AST::child, lexer::col, lexer::token::comma, lexer::curToken, AST::functionDefStmt, AST::identifier, lexer::token::identifier, lexer::token::kFunc, lexer::token::kind, lexer::token::leftParentheses, parser::lex, lexer::line, parser::makeNotMatch(), parser::parseBlockStmt(), parser::parseIdentifier(), lexer::token::rightParentheses, and lexer::scan().
Referenced by parser::parseStmts().
parseIdentifier()
AST parseIdentifier ()
Definition at line 32 of file parser.cpp.
References lexer::curToken, AST::identifier, lexer::token::identifier, lexer::token::kind, parser::lex, parser::makeNotMatch(), and lexer::scan().
Referenced by parser::parseClosureDefinition(), parser::parseFunctionDefinition(), parser::parseFunctionDefStmt(), parser::parseLetStmt(), parser::parseRangeBasedForStmt(), parser::parseSubscriptExpression(), parser::parseTryCatchStmt(), and parser::parseWithStmt().
parseIfStmt()
AST parseIfStmt ()
Definition at line 713 of file parser.cpp.
References lexer::col, lexer::curToken, AST::ifElseStmt, AST::ifStmt, lexer::token::kElse, lexer::token::kIf, lexer::token::kind, lexer::token::leftParentheses, parser::lex, lexer::line, parser::makeNotMatch(), parser::parseLvalueExpression(), parser::parseStmts(), lexer::token::rightParentheses, and lexer::scan().
Referenced by parser::parseStmts().
parseLetStmt()
AST parseLetStmt ()
Definition at line 583 of file parser.cpp.
References lexer::token::assignSign, lexer::col, lexer::token::comma, lexer::curToken, lexer::token::kind, lexer::token::kLet, AST::letAssignmentPair, AST::letStmt, parser::lex, lexer::line, parser::makeNotMatch(), parser::parseIdentifier(), parser::parseLvalueExpression(), and lexer::scan().
Referenced by parser::parseStmts().
parseListLiteral()
AST parseListLiteral ()
Definition at line 93 of file parser.cpp.
References AST::child, lexer::col, lexer::token::comma, lexer::curToken, lexer::token::kind, lexer::token::leftBracket, parser::lex, lexer::line, AST::listLiteral, parser::makeNotMatch(), parser::parseLvalueExpression(), lexer::token::rightBracket, and lexer::scan().
Referenced by parser::parsePrimary().
parseLogicAndExpression()
AST parseLogicAndExpression ()
Definition at line 491 of file parser.cpp.
References lexer::col, lexer::curToken, lexer::token::kind, parser::lex, lexer::line, lexer::token::logicAnd, AST::logicAndExpression, lexer::token::logicOr, parser::makeNotMatch(), AST::operators, parser::parseBinaryExpression(), and lexer::scan().
Referenced by parser::parseLvalueExpression().
parseLogicEqualExpression()
AST parseLogicEqualExpression ()
Definition at line 431 of file parser.cpp.
References lexer::col, lexer::curToken, lexer::token::equal, lexer::token::greaterEqual, lexer::token::greaterThan, lexer::token::kind, lexer::token::lessEqual, lexer::token::lessThan, parser::lex, lexer::line, AST::logicEqualExpression, parser::makeNotMatch(), lexer::token::notEqual, AST::operators, parser::parseBinaryShiftExpression(), and lexer::scan().
Referenced by parser::parseBinaryExpression().
parseLvalueExpression()
AST parseLvalueExpression ()
Definition at line 516 of file parser.cpp.
References parser::parseLogicAndExpression().
Referenced by parser::parseArguments(), parser::parseAssignmentExpression(), parser::parseForStmt(), parser::parseIfStmt(), parser::parseLetStmt(), parser::parseListLiteral(), parser::parseObjectLiteral(), parser::parsePrimary(), parser::parseRangeBasedForStmt(), parser::parseReturnStmt(), parser::parseStmts(), parser::parseSubscriptExpression(), parser::parseThrowStmt(), parser::parseWhileStmt(), and parser::parseWithStmt().
parseMemberExpression()
AST parseMemberExpression ()
Definition at line 260 of file parser.cpp.
References lexer::col, lexer::curToken, lexer::token::dot, lexer::token::kind, parser::lex, lexer::line, parser::makeNotMatch(), AST::memberExpression, parser::parsePrimary(), parser::parseSubscriptExpression(), and lexer::scan().
Referenced by parser::parseAssignmentExpression(), and parser::parseUniqueExpression().
parseMultiplicationExpression()
AST parseMultiplicationExpression ()
Definition at line 353 of file parser.cpp.
References lexer::token::asterisk, lexer::col, lexer::curToken, lexer::token::kind, parser::lex, lexer::line, parser::makeNotMatch(), AST::multiplicationExpression, AST::operators, parser::parseUniqueExpression(), lexer::token::percentSign, lexer::scan(), and lexer::token::slash.
Referenced by parser::parseAdditionExpression().
parseObjectLiteral()
AST parseObjectLiteral ()
Definition at line 113 of file parser.cpp.
References AST::child, lexer::col, lexer::token::colon, lexer::token::comma, lexer::curToken, AST::identifier, lexer::token::identifier, lexer::token::kind, lexer::token::leftBraces, parser::lex, lexer::line, parser::makeNotMatch(), AST::memberPair, AST::objectLiteral, parser::parseLvalueExpression(), lexer::token::rightBraces, lexer::scan(), and lexer::token::string.
Referenced by parser::parsePrimary().
parsePrimary()
AST parsePrimary ()
Definition at line 283 of file parser.cpp.
References lexer::col, lexer::curToken, lexer::token::kind, lexer::token::leftParentheses, parser::lex, lexer::line, parser::makeNotMatch(), parser::parseBasicLiterals(), parser::parseClosureDefinition(), parser::parseFunctionDefinition(), parser::parseListLiteral(), parser::parseLvalueExpression(), parser::parseObjectLiteral(), parser::parseSubscriptExpression(), lexer::token::rightParentheses, and lexer::scan().
Referenced by parser::parseMemberExpression().
parseRangeBasedForStmt()
AST parseRangeBasedForStmt ()
Definition at line 680 of file parser.cpp.
References lexer::col, lexer::curToken, lexer::token::kForEach, lexer::token::kIn, lexer::token::kind, lexer::token::leftParentheses, parser::lex, lexer::line, parser::makeNotMatch(), parser::parseIdentifier(), parser::parseLvalueExpression(), parser::parseStmts(), AST::rangeBasedForStmt, lexer::token::rightParentheses, and lexer::scan().
Referenced by parser::parseStmts().
parseReturnStmt()
AST parseReturnStmt ()
Definition at line 745 of file parser.cpp.
References lexer::col, lexer::curToken, lexer::token::kind, lexer::token::kReturn, parser::lex, lexer::line, parser::makeNotMatch(), parser::parseLvalueExpression(), AST::returnStmt, and lexer::scan().
Referenced by parser::parseStmts().
parseStmts()
AST parseStmts ()
Definition at line 776 of file parser.cpp.
References parser::parseAssignmentExpression(), parser::parseBlockStmt(), parser::parseBreakStmt(), parser::parseContinueStmt(), parser::parseForStmt(), parser::parseFunctionDefStmt(), parser::parseIfStmt(), parser::parseLetStmt(), parser::parseLvalueExpression(), parser::parseRangeBasedForStmt(), parser::parseReturnStmt(), parser::parseThrowStmt(), parser::parseTryCatchStmt(), parser::parseWhileStmt(), and parser::parseWithStmt().
Referenced by interactiveShell(), parser::parseBlockStmt(), parser::parseFile(), parser::parseForStmt(), parser::parseIfStmt(), parser::parseRangeBasedForStmt(), parser::parseWhileStmt(), and parser::parseWithStmt().
parseSubscriptExpression()
AST parseSubscriptExpression ()
Definition at line 46 of file parser.cpp.
References lexer::token::col, lexer::col, lexer::curToken, lexer::dropState(), AST::invokingExpression, lexer::token::kind, AST::leaf, lexer::token::leftBracket, lexer::token::leftParentheses, parser::lex, lexer::token::line, lexer::line, parser::makeNotMatch(), parser::parseArguments(), parser::parseIdentifier(), parser::parseLvalueExpression(), lexer::returnState(), lexer::token::rightBracket, lexer::saveState(), lexer::scan(), and AST::subscriptExpression.
Referenced by parser::parseMemberExpression(), and parser::parsePrimary().
parseThrowStmt()
AST parseThrowStmt ()
Definition at line 890 of file parser.cpp.
References lexer::col, lexer::curToken, lexer::token::kind, lexer::token::kThrow, parser::lex, lexer::line, parser::parseLvalueExpression(), lexer::scan(), and AST::throwStmt.
Referenced by parser::parseStmts().
parseTryCatchStmt()
AST parseTryCatchStmt ()
Definition at line 868 of file parser.cpp.
References lexer::col, lexer::curToken, lexer::token::kAs, lexer::token::kCatch, lexer::token::kind, lexer::token::kTry, parser::lex, lexer::line, parser::parseBlockStmt(), parser::parseIdentifier(), lexer::scan(), and AST::tryCatchStmt.
Referenced by parser::parseStmts().
parseUniqueExpression()
AST parseUniqueExpression ()
Definition at line 322 of file parser.cpp.
References lexer::token::asterisk, lexer::token::binaryAnd, lexer::col, lexer::curToken, lexer::token::decrementSign, lexer::dropState(), lexer::token::incrementSign, lexer::token::kind, parser::lex, lexer::line, parser::makeNotMatch(), lexer::token::minus, AST::operators, parser::parseMemberExpression(), lexer::returnState(), lexer::saveState(), lexer::scan(), lexer::token::sharp, and AST::uniqueExpression.
Referenced by parser::parseMultiplicationExpression().
parseWhileStmt()
AST parseWhileStmt ()
Definition at line 615 of file parser.cpp.
References lexer::col, lexer::curToken, lexer::token::kind, lexer::token::kWhile, lexer::token::leftParentheses, parser::lex, lexer::line, parser::makeNotMatch(), parser::parseLvalueExpression(), parser::parseStmts(), lexer::token::rightParentheses, lexer::scan(), and AST::whileStmt.
Referenced by parser::parseStmts().
parseWithStmt()
AST parseWithStmt ()
Definition at line 936 of file parser.cpp.
References lexer::col, lexer::token::colon, lexer::curToken, lexer::token::kind, lexer::token::kWith, lexer::token::leftParentheses, parser::lex, lexer::line, parser::makeNotMatch(), parser::parseIdentifier(), parser::parseLvalueExpression(), parser::parseStmts(), lexer::token::rightParentheses, lexer::scan(), and AST::withStmt.
Referenced by parser::parseStmts().
Member Data Documentation
lex
lexer& lex private
Definition at line 14 of file parser.hpp.
Referenced by parser::parseAdditionExpression(), parser::parseArguments(), parser::parseAssignmentExpression(), parser::parseBasicLiterals(), parser::parseBinaryExpression(), parser::parseBinaryShiftExpression(), parser::parseBlockStmt(), parser::parseBreakStmt(), parser::parseClosureDefinition(), parser::parseContinueStmt(), parser::parseFile(), parser::parseForStmt(), parser::parseFunctionDefinition(), parser::parseFunctionDefStmt(), parser::parseIdentifier(), parser::parseIfStmt(), parser::parseLetStmt(), parser::parseListLiteral(), parser::parseLogicAndExpression(), parser::parseLogicEqualExpression(), parser::parseMemberExpression(), parser::parseMultiplicationExpression(), parser::parseObjectLiteral(), parser::parsePrimary(), parser::parser(), parser::parseRangeBasedForStmt(), parser::parseReturnStmt(), parser::parseSubscriptExpression(), parser::parseThrowStmt(), parser::parseTryCatchStmt(), parser::parseUniqueExpression(), parser::parseWhileStmt(), and parser::parseWithStmt().
The documentation for this class was generated from the following files:
frontend/parser.hpp
frontend/parser.cpp