reXscript: utf8Unicode Class Reference
utf8Unicode Class Reference
#include <utfutils.hpp>
Static Public Member Functions
static bool utf8ToUnicode (const std::string &utf8, std::wstring &unicode)
static void unicodeToUtf8 (const std::wstring &unicode, std::string &utf8)
Static Private Member Functions
static bool checkLength (unsigned int start, unsigned int offset, unsigned int end)
Detailed Description
Definition at line 7 of file utfutils.hpp.
Member Function Documentation
checkLength()
static bool checkLength (unsigned int start, unsigned int offset, unsigned int end) inline static private
Definition at line 131 of file utfutils.hpp.
Referenced by utf8ToUnicode().
unicodeToUtf8()
static void unicodeToUtf8 (const std::wstring & unicode, std::string & utf8) inline static
Definition at line 73 of file utfutils.hpp.
Referenced by rex::wstring2string().
utf8ToUnicode()
static bool utf8ToUnicode (const std::string & utf8, std::wstring & unicode) inline static
Definition at line 9 of file utfutils.hpp.
References checkLength().
Referenced by rex::string2wstring().
The documentation for this class was generated from the following file:
share/utfutils.hpp