reXscript: interpreter Class Reference
interpreter Class Reference
The interpreter class for reXscript.
#include <interpreter.hpp>
Public Member Functions
vsize getCurStackIdx ()
Get the current index of the stack.
void backToStackIdx (vsize stkIdx)
Set the current index of the stack.
interpreter (const managedPtr< environment > &env, const managedPtr< value > &moduleCxt)
Construct a new interpreter object.
value invokeFunc (managedPtr< value > func, const vec< value > &args, const managedPtr< value > &passThisPtr)
vstr getBacktrace ()
value opAdd (value &a, value &b)
value opSub (value &a, value &b)
value opMul (value &a, value &b)
value opDiv (value &a, value &b)
value opMod (value &a, value &b)
value opBinaryShiftLeft (value &a, value &b)
value opBinaryShiftRight (value &a, value &b)
value opEqual (value &a, value &b)
value opNotEqual (value &a, value &b)
value opGreaterEqual (value &a, value &b)
value opLessEqual (value &a, value &b)
value opGreaterThan (value &a, value &b)
value opLessThan (value &a, value &b)
value opBinaryOr (value &a, value &b)
value opBinaryAnd (value &a, value &b)
value opBinaryXor (value &a, value &b)
value opLogicAnd (value &a, value &b)
value opLogicOr (value &a, value &b)
value interpretLvalueExpressions (const AST &target)
value interpretAssignments (const AST &target)
value interpret (const AST &target)
Static Public Member Functions
static value makeErr (const vstr &errName, const vstr &errMsg)
Public Attributes
vec< environment::stackFrame > stack
A stack for storing the stack frames for function calls.
managedPtr< value > moduleCxt
The context of the module currently being interpreted.
managedPtr< environment > env
A pointer to the environment in which the interpreter is running.
value::cxtObject interpreterCxt
The interpreter context for storing global variables for the interpreter.
Detailed Description
The interpreter class for reXscript.
Definition at line 139 of file interpreter.hpp.
Constructor & Destructor Documentation
interpreter()
interpreter (const managedPtr< environment > & env, const managedPtr< value > & moduleCxt)
Construct a new interpreter object.
Parameters
env The environment in which the interpreter will be running
moduleCxt The context of the module currently being interpreted
Definition at line 71 of file interpreter.cpp.
Member Function Documentation
backToStackIdx()
void backToStackIdx (vsize stkIdx)
Set the current index of the stack.
Parameters
stkIdx The index to set the current stack frame to
Definition at line 890 of file interpreter.cpp.
Referenced by interpreter::interpret().
getBacktrace()
vstr getBacktrace ()
Definition at line 1426 of file interpreter.cpp.
Referenced by interactiveShell(), and loadFile().
getCurStackIdx()
vsize getCurStackIdx ()
Get the current index of the stack.
Returns
The index of the current stack frame
Definition at line 886 of file interpreter.cpp.
Referenced by interpreter::interpret().
interpret()
value interpret (const AST & target)
Definition at line 145 of file interpreter.cpp.
References AST::additionExpression, value::funcObject::argsName, AST::assignmentExpression, lexer::token::asterisk, interpreter::backToStackIdx(), AST::basicLiterals, lexer::token::basicVal, AST::binaryExpression, AST::binaryShiftExpression, AST::blockStmt, lexer::token::boolean, AST::breakStmt, AST::child, value::funcObject::code, AST::continueStmt, lexer::token::decimal, lexer::token::decrementSign, value::deepCopy(), interpreter::env, AST::forStmt, value::lambdaObject::func, AST::functionDefinition, AST::functionDefStmt, signalException::get(), value::getBool(), interpreter::getCurStackIdx(), value::getDeci(), value::getInt(), rex::stringMethods::getMethodsCxt(), rex::vecMethods::getMethodsCxt(), value::getRef(), value::getStr(), AST::identifier, AST::ifElseStmt, AST::ifStmt, lexer::token::incrementSign, lexer::token::integer, interpreter::interpret(), interpreter::interpretAssignments(), interpreter::interpreterCxt, interpreter::interpretLvalueExpressions(), interpreter::invokeFunc(), AST::invokingExpression, value::isRef(), AST::kind, lexer::token::kind, value::kind, lexer::token::kNull, AST::lambdaDefinition, AST::leaf, AST::letStmt, AST::listLiteral, AST::logicAndExpression, AST::logicEqualExpression, interpreter::makeErr(), rex::managePtr(), AST::memberExpression, value::members, lexer::token::minus, interpreter::moduleCxt, value::funcObject::moduleCxt, AST::multiplicationExpression, AST::objectLiteral, value::lambdaObject::outerCxt, AST::rangeBasedForStmt, value::refObj, AST::returnStmt, interpreter::stack, lexer::token::string, value::strObj, lexer::token::strVal, AST::subscriptExpression, AST::throwStmt, AST::tryCatchStmt, AST::uniqueExpression, lexer::token::vBasicValue::vBool, value::vBool, lexer::token::vBasicValue::vDeci, value::vDeci, value::vecObj, lexer::token::vBasicValue::vInt, value::vInt, value::vStr, value::vVec, and AST::whileStmt.
Referenced by rex::importExternModuleEx(), rex::importExternPackageEx(), interpreter::interpret(), and interpreter::invokeFunc().
interpretAssignments()
value interpretAssignments (const AST & target)
Definition at line 670 of file interpreter.cpp.
References AST::child, value::getBool(), value::getDeci(), value::getInt(), value::getRef(), value::isRef(), value::kind, value::refObj, and valueKindComparator.
Referenced by interpreter::interpret().
interpretLvalueExpressions()
value interpretLvalueExpressions (const AST & target)
Definition at line 624 of file interpreter.cpp.
References AST::child.
Referenced by interpreter::interpret().
invokeFunc()
value invokeFunc (managedPtr< value > func, const vec< value > & args, const managedPtr< value > & passThisPtr)
Definition at line 77 of file interpreter.cpp.
References interpreter::env, signalReturn::get(), interpreter::interpret(), interpreter::makeErr(), rex::managePtr(), value::refObj, interpreter::stack, value::vFunc, value::vLambda, and value::vNativeFuncPtr.
Referenced by rex::importExternModuleEx(), rex::importExternPackageEx(), and interpreter::interpret().
makeErr()
value makeErr (const vstr & errName, const vstr & errMsg) static
Definition at line 138 of file interpreter.cpp.
References rex::stringMethods::getMethodsCxt(), rex::managePtr(), and value::members.
Referenced by rex::importExternModule(), rex::importExternPackage(), rex::importNativeModule(), interpreter::interpret(), interpreter::invokeFunc(), and rex::nativeFn().
opAdd()
value opAdd (value & a, value & b)
Definition at line 894 of file interpreter.cpp.
References value::getBool(), value::getDeci(), value::getInt(), value::getRef(), value::isRef(), value::kind, rex::managePtr(), value::members, and valueKindComparator.
opBinaryAnd()
value opBinaryAnd (value & a, value & b)
Definition at line 1330 of file interpreter.cpp.
References value::getBool(), value::getInt(), value::getRef(), value::isRef(), value::kind, rex::managePtr(), value::members, and valueKindComparator.
opBinaryOr()
value opBinaryOr (value & a, value & b)
Definition at line 1306 of file interpreter.cpp.
References value::getBool(), value::getInt(), value::getRef(), value::isRef(), value::kind, rex::managePtr(), value::members, and valueKindComparator.
opBinaryShiftLeft()
value opBinaryShiftLeft (value & a, value & b)
Definition at line 1054 of file interpreter.cpp.
References value::getBool(), value::getInt(), value::getRef(), value::isRef(), value::kind, rex::managePtr(), value::members, and valueKindComparator.
opBinaryShiftRight()
value opBinaryShiftRight (value & a, value & b)
Definition at line 1078 of file interpreter.cpp.
References value::getBool(), value::getInt(), value::getRef(), value::isRef(), value::kind, rex::managePtr(), value::members, and valueKindComparator.
opBinaryXor()
value opBinaryXor (value & a, value & b)
Definition at line 1354 of file interpreter.cpp.
References value::getBool(), value::getInt(), value::getRef(), value::isRef(), value::kind, rex::managePtr(), value::members, and valueKindComparator.
opDiv()
value opDiv (value & a, value & b)
Definition at line 996 of file interpreter.cpp.
References value::getBool(), value::getDeci(), value::getInt(), value::getRef(), value::isRef(), value::kind, rex::managePtr(), value::members, and valueKindComparator.
opEqual()
value opEqual (value & a, value & b)
Definition at line 1102 of file interpreter.cpp.
References value::getBool(), value::getDeci(), value::getInt(), value::getRef(), value::isRef(), value::kind, rex::managePtr(), value::members, and valueKindComparator.
opGreaterEqual()
value opGreaterEqual (value & a, value & b)
Definition at line 1170 of file interpreter.cpp.
References value::getBool(), value::getDeci(), value::getInt(), value::getRef(), value::isRef(), value::kind, rex::managePtr(), value::members, and valueKindComparator.
opGreaterThan()
value opGreaterThan (value & a, value & b)
Definition at line 1238 of file interpreter.cpp.
References value::getBool(), value::getDeci(), value::getInt(), value::getRef(), value::isRef(), value::kind, rex::managePtr(), value::members, and valueKindComparator.
opLessEqual()
value opLessEqual (value & a, value & b)
Definition at line 1204 of file interpreter.cpp.
References value::getBool(), value::getDeci(), value::getInt(), value::getRef(), value::isRef(), value::kind, rex::managePtr(), value::members, and valueKindComparator.
opLessThan()
value opLessThan (value & a, value & b)
Definition at line 1272 of file interpreter.cpp.
References value::getBool(), value::getDeci(), value::getInt(), value::getRef(), value::isRef(), value::kind, rex::managePtr(), value::members, and valueKindComparator.
opLogicAnd()
value opLogicAnd (value & a, value & b)
Definition at line 1378 of file interpreter.cpp.
References value::getBool(), value::getInt(), value::getRef(), value::isRef(), value::kind, rex::managePtr(), value::members, and valueKindComparator.
opLogicOr()
value opLogicOr (value & a, value & b)
Definition at line 1402 of file interpreter.cpp.
References value::getBool(), value::getInt(), value::getRef(), value::isRef(), value::kind, rex::managePtr(), value::members, and valueKindComparator.
opMod()
value opMod (value & a, value & b)
Definition at line 1030 of file interpreter.cpp.
References value::getBool(), value::getInt(), value::getRef(), value::isRef(), value::kind, rex::managePtr(), value::members, and valueKindComparator.
opMul()
value opMul (value & a, value & b)
Definition at line 962 of file interpreter.cpp.
References value::getBool(), value::getDeci(), value::getInt(), value::getRef(), value::isRef(), value::kind, rex::managePtr(), value::members, and valueKindComparator.
opNotEqual()
value opNotEqual (value & a, value & b)
Definition at line 1136 of file interpreter.cpp.
References value::getBool(), value::getDeci(), value::getInt(), value::getRef(), value::isRef(), value::kind, rex::managePtr(), value::members, and valueKindComparator.
opSub()
value opSub (value & a, value & b)
Definition at line 928 of file interpreter.cpp.
References value::getBool(), value::getDeci(), value::getInt(), value::getRef(), value::isRef(), value::kind, rex::managePtr(), value::members, and valueKindComparator.
Member Data Documentation
env
managedPtr<environment> env
A pointer to the environment in which the interpreter is running.
Definition at line 154 of file interpreter.hpp.
Referenced by rex::importExternModule(), rex::importExternModuleEx(), rex::importExternPackage(), rex::importExternPackageEx(), rex::importNativeModule(), rex::importNativeModuleEx(), interactiveShell(), interpreter::interpret(), interpreter::invokeFunc(), and rex::nativeFn().
interpreterCxt
value::cxtObject interpreterCxt
The interpreter context for storing global variables for the interpreter.
Definition at line 159 of file interpreter.hpp.
Referenced by rex::importExternModuleEx(), interactiveShell(), and interpreter::interpret().
moduleCxt
managedPtr<value> moduleCxt
The context of the module currently being interpreted.
Definition at line 149 of file interpreter.hpp.
Referenced by rex::importEx(), rex::importExternModuleEx(), rex::importExternPackageEx(), rex::importNativeModuleEx(), and interpreter::interpret().
stack
vec<environment::stackFrame> stack
A stack for storing the stack frames for function calls.
Definition at line 144 of file interpreter.hpp.
Referenced by interactiveShell(), interpreter::interpret(), and interpreter::invokeFunc().
The documentation for this class was generated from the following files:
interpreter/interpreter.hpp
interpreter/interpreter.cpp