reXscript: value Class Reference
value Class Reference
#include <value.hpp>
Classes
struct funcObject
struct lambdaObject
union vValue
Public Types
enum class vKind : uint16_t {
vNull , vInt , vDeci , vBool ,
vStr , vBytes , vVec , vObject ,
vFunc , vLambda , vNativeFuncPtr , vRef ,
vLinkedList , vLinkedListIter
}
using linkedListObject = std::list< managedPtr< value > >
using vecObject = vec< managedPtr< value > >
using cxtObject = map< vstr, managedPtr< value > >
using nativeFuncPtr = std::function< value(void *, vec< value >, const managedPtr< value > &)>
Public Member Functions
bool isRef ()
void deepCopy (value &dest)
vint & getInt ()
vbool & getBool ()
vdeci & getDeci ()
value & getRef ()
vecObject & getVec ()
funcObject & getFunc ()
lambdaObject & getLambda ()
linkedListObject & getLinkedList ()
vstr & getStr ()
vbytes & getBytes ()
managedPtr< value > operator[] (const vstr &v)
operator vstr ()
value (const vstr &v, cxtObject members)
value (const vbytes &v, cxtObject members)
value (const vecObject &v, cxtObject members)
value (const linkedListObject &v, cxtObject members)
value (const linkedListObject::iterator &v)
value (cxtObject members)
value (const funcObject &v)
value (const lambdaObject &v)
value (const nativeFuncPtr &v)
value (const managedPtr< value > &v)
value (vint v)
value (vdeci v)
value (vbool v)
value (unknownPtr unk)
value ()
vstr getKind ()
Public Attributes
enum rex::value::vKind kind
union rex::value::vValue basicValue
managedPtr< value > refObj
managedPtr< vstr > strObj
managedPtr< vbytes > bytesObj
managedPtr< vecObject > vecObj
managedPtr< funcObject > funcObj
managedPtr< lambdaObject > lambdaObj
managedPtr< nativeFuncPtr > nativeFuncObj
managedPtr< linkedListObject > linkedListObj
managedPtr< linkedListObject::iterator > linkedListIterObj
cxtObject members
Detailed Description
Definition at line 13 of file value.hpp.
Member Typedef Documentation
cxtObject
using cxtObject = map<vstr, managedPtr<value> >
Definition at line 17 of file value.hpp.
linkedListObject
using linkedListObject = std::list<managedPtr<value> >
Definition at line 15 of file value.hpp.
nativeFuncPtr
using nativeFuncPtr = std::function<value(void *, vec<value>, const managedPtr<value> &)>
Definition at line 18 of file value.hpp.
vecObject
using vecObject = vec<managedPtr<value> >
Definition at line 16 of file value.hpp.
Member Enumeration Documentation
vKind
enum vKind : uint16_t strong
Enumerator
vNull
vInt
vDeci
vBool
vStr
vBytes
vVec
vObject
vFunc
vLambda
vNativeFuncPtr
vRef
vLinkedList
vLinkedListIter
Definition at line 39 of file value.hpp.
Constructor & Destructor Documentation
value() [1/15]
value (const vstr & v, value::cxtObject members)
Definition at line 141 of file value.cpp.
value() [2/15]
value (const vbytes & v, value::cxtObject members)
Definition at line 282 of file value.cpp.
value() [3/15]
value (const vecObject & v, value::cxtObject members)
Definition at line 146 of file value.cpp.
value() [4/15]
value (const linkedListObject & v, value::cxtObject members)
Definition at line 301 of file value.cpp.
value() [5/15]
value (const linkedListObject::iterator & v)
Definition at line 327 of file value.cpp.
value() [6/15]
value (value::cxtObject members)
Definition at line 177 of file value.cpp.
value() [7/15]
value (const funcObject & v)
Definition at line 151 of file value.cpp.
value() [8/15]
value (const lambdaObject & v)
Definition at line 156 of file value.cpp.
value() [9/15]
value (const nativeFuncPtr & v)
Definition at line 181 of file value.cpp.
value() [10/15]
value (const managedPtr< value > & v)
Definition at line 186 of file value.cpp.
value() [11/15]
value (vint v)
Definition at line 161 of file value.cpp.
value() [12/15]
value (vdeci v)
Definition at line 165 of file value.cpp.
value() [13/15]
value (vbool v)
Definition at line 169 of file value.cpp.
value() [14/15]
value (unknownPtr unk)
Definition at line 278 of file value.cpp.
value() [15/15]
value ()
Definition at line 173 of file value.cpp.
Member Function Documentation
deepCopy()
void deepCopy (value & dest)
Definition at line 35 of file value.cpp.
References value::bytesObj, value::deepCopy(), value::funcObj, value::getRef(), value::kind, value::lambdaObj, value::linkedListIterObj, value::linkedListObj, rex::managePtr(), value::members, value::strObj, value::vBool, value::vBytes, value::vDeci, value::vecObj, value::vFunc, value::vInt, value::vLambda, value::vLinkedList, value::vLinkedListIter, value::vNativeFuncPtr, value::vNull, value::vObject, value::vRef, value::vStr, and value::vVec.
Referenced by value::deepCopy(), interpreter::interpret(), and rex::nativeFn().
getBool()
vbool & getBool ()
Definition at line 105 of file value.cpp.
References value::basicValue, and value::vValue::vBool.
Referenced by interpreter::interpret(), interpreter::interpretAssignments(), rex::nativeFn(), interpreter::opAdd(), interpreter::opBinaryAnd(), interpreter::opBinaryOr(), interpreter::opBinaryShiftLeft(), interpreter::opBinaryShiftRight(), interpreter::opBinaryXor(), interpreter::opDiv(), interpreter::opEqual(), interpreter::opGreaterEqual(), interpreter::opGreaterThan(), interpreter::opLessEqual(), interpreter::opLessThan(), interpreter::opLogicAnd(), interpreter::opLogicOr(), interpreter::opMod(), interpreter::opMul(), interpreter::opNotEqual(), and interpreter::opSub().
getBytes()
vbytes & getBytes ()
Definition at line 287 of file value.cpp.
References value::bytesObj.
Referenced by rex::nativeFn().
getDeci()
vdeci & getDeci ()
Definition at line 109 of file value.cpp.
References value::basicValue, and value::vValue::vDeci.
Referenced by interpreter::interpret(), interpreter::interpretAssignments(), rex::nativeFn(), interpreter::opAdd(), interpreter::opDiv(), interpreter::opEqual(), interpreter::opGreaterEqual(), interpreter::opGreaterThan(), interpreter::opLessEqual(), interpreter::opLessThan(), interpreter::opMul(), interpreter::opNotEqual(), and interpreter::opSub().
getFunc()
value::funcObject & getFunc ()
Definition at line 127 of file value.cpp.
References value::funcObj.
getInt()
vint & getInt ()
Definition at line 101 of file value.cpp.
References value::basicValue, and value::vValue::vInt.
Referenced by interpreter::interpret(), interpreter::interpretAssignments(), rex::nativeFn(), interpreter::opAdd(), interpreter::opBinaryAnd(), interpreter::opBinaryOr(), interpreter::opBinaryShiftLeft(), interpreter::opBinaryShiftRight(), interpreter::opBinaryXor(), interpreter::opDiv(), interpreter::opEqual(), interpreter::opGreaterEqual(), interpreter::opGreaterThan(), interpreter::opLessEqual(), interpreter::opLessThan(), interpreter::opLogicAnd(), interpreter::opLogicOr(), interpreter::opMod(), interpreter::opMul(), interpreter::opNotEqual(), and interpreter::opSub().
getKind()
vstr getKind ()
Definition at line 329 of file value.cpp.
References value::getKind(), value::getRef(), value::kind, value::vBool, value::vBytes, value::vDeci, value::vFunc, value::vInt, value::vLambda, value::vLinkedList, value::vLinkedListIter, value::vNativeFuncPtr, value::vNull, value::vObject, value::vRef, value::vStr, and value::vVec.
Referenced by value::getKind(), interpreter::opAdd(), interpreter::opBinaryAnd(), interpreter::opBinaryOr(), interpreter::opBinaryShiftLeft(), interpreter::opBinaryShiftRight(), interpreter::opBinaryXor(), interpreter::opDiv(), interpreter::opEqual(), interpreter::opGreaterEqual(), interpreter::opGreaterThan(), interpreter::opLessEqual(), interpreter::opLessThan(), interpreter::opLogicAnd(), interpreter::opLogicOr(), interpreter::opMod(), interpreter::opMul(), interpreter::opNotEqual(), and interpreter::opSub().
getLambda()
value::lambdaObject & getLambda ()
Definition at line 134 of file value.cpp.
References value::lambdaObj.
getLinkedList()
value::linkedListObject & getLinkedList ()
Definition at line 294 of file value.cpp.
References value::linkedListObj.
Referenced by rex::linkedListMethods::iterator::getMethodsCxt(), rex::hashMapMethods::iterator::getMethodsCxt(), and rex::hashMapMethods::keysIterator::getMethodsCxt().
getRef()
value & getRef ()
Definition at line 113 of file value.cpp.
References value::refObj.
Referenced by value::deepCopy(), value::getKind(), and interpreter::interpret().
getStr()
vstr & getStr ()
Definition at line 197 of file value.cpp.
References value::strObj.
Referenced by interactiveShell(), interpreter::interpret(), and rex::nativeFn().
getVec()
value::vecObject & getVec ()
Definition at line 120 of file value.cpp.
References value::vecObj.
Referenced by interpreter::interpret().
isRef()
bool isRef ()
Definition at line 31 of file value.cpp.
References value::kind, and value::vRef.
Referenced by interpreter::interpret(), interpreter::interpretAssignments(), rex::nativeFn(), interpreter::opAdd(), interpreter::opBinaryAnd(), interpreter::opBinaryOr(), interpreter::opBinaryShiftLeft(), interpreter::opBinaryShiftRight(), interpreter::opBinaryXor(), interpreter::opDiv(), interpreter::opEqual(), interpreter::opGreaterEqual(), interpreter::opGreaterThan(), interpreter::opLessEqual(), interpreter::opLessThan(), interpreter::opLogicAnd(), interpreter::opLogicOr(), interpreter::opMod(), interpreter::opMul(), interpreter::opNotEqual(), and interpreter::opSub().
operator vstr()
operator vstr ()
Definition at line 204 of file value.cpp.
References rex::getPrintableBytes(), and rex::string2wstring().
operator[]()
managedPtr< value > operator[] (const vstr & v)
Definition at line 190 of file value.cpp.
References rex::managePtr(), and value::members.
Member Data Documentation
basicValue
union rex::value::vValue basicValue
Referenced by value::getBool(), value::getDeci(), and value::getInt().
bytesObj
managedPtr<vbytes> bytesObj
Definition at line 76 of file value.hpp.
Referenced by value::deepCopy(), and value::getBytes().
funcObj
managedPtr<funcObject> funcObj
Definition at line 78 of file value.hpp.
Referenced by value::deepCopy(), and value::getFunc().
kind
enum rex::value::vKind kind
Referenced by value::deepCopy(), value::getKind(), interpreter::interpret(), interpreter::interpretAssignments(), value::isRef(), rex::nativeFn(), interpreter::opAdd(), interpreter::opBinaryAnd(), interpreter::opBinaryOr(), interpreter::opBinaryShiftLeft(), interpreter::opBinaryShiftRight(), interpreter::opBinaryXor(), interpreter::opDiv(), interpreter::opEqual(), interpreter::opGreaterEqual(), interpreter::opGreaterThan(), interpreter::opLessEqual(), interpreter::opLessThan(), interpreter::opLogicAnd(), interpreter::opLogicOr(), interpreter::opMod(), interpreter::opMul(), interpreter::opNotEqual(), and interpreter::opSub().
lambdaObj
managedPtr<lambdaObject> lambdaObj
Definition at line 79 of file value.hpp.
Referenced by value::deepCopy(), and value::getLambda().
linkedListIterObj
managedPtr<linkedListObject::iterator> linkedListIterObj
Definition at line 82 of file value.hpp.
Referenced by value::deepCopy().
linkedListObj
managedPtr<linkedListObject> linkedListObj
Definition at line 81 of file value.hpp.
Referenced by value::deepCopy(), and value::getLinkedList().
members
cxtObject members
Definition at line 85 of file value.hpp.
Referenced by value::deepCopy(), interpreter::interpret(), interpreter::makeErr(), rex::nativeFn(), interpreter::opAdd(), interpreter::opBinaryAnd(), interpreter::opBinaryOr(), interpreter::opBinaryShiftLeft(), interpreter::opBinaryShiftRight(), interpreter::opBinaryXor(), interpreter::opDiv(), interpreter::opEqual(), value::operator[](), interpreter::opGreaterEqual(), interpreter::opGreaterThan(), interpreter::opLessEqual(), interpreter::opLessThan(), interpreter::opLogicAnd(), interpreter::opLogicOr(), interpreter::opMod(), interpreter::opMul(), interpreter::opNotEqual(), and interpreter::opSub().
nativeFuncObj
managedPtr<nativeFuncPtr> nativeFuncObj
Definition at line 80 of file value.hpp.
refObj
managedPtr<value> refObj
Definition at line 74 of file value.hpp.
Referenced by value::getRef(), rex::getSelfRef(), interpreter::interpret(), interpreter::interpretAssignments(), and interpreter::invokeFunc().
strObj
managedPtr<vstr> strObj
Definition at line 75 of file value.hpp.
Referenced by value::deepCopy(), value::getStr(), and interpreter::interpret().
vecObj
managedPtr<vecObject> vecObj
Definition at line 77 of file value.hpp.
Referenced by value::deepCopy(), value::getVec(), and interpreter::interpret().
The documentation for this class was generated from the following files:
interpreter/value.hpp
interpreter/value.cpp