reXscript: lexer Class Reference
lexer Class Reference
#include <lexer.hpp>
Classes
struct lexerState
struct token
Public Member Functions
void getCh ()
lexer (std::wistream &ss)
void saveState ()
void returnState ()
void dropState ()
token scan ()
token alphaStart ()
token strStart ()
token digitStart ()
token minusStart ()
token plusStart ()
token asteriskStart ()
token slashStart ()
token percentSignStart ()
token equalStart ()
token notStart ()
token lessStart ()
token greaterStart ()
token semicolonStart ()
token colonStart ()
token commaStart ()
token dotStart ()
token leftParenthesesStart ()
token rightParenthesesStart ()
token leftBracketStart ()
token rightBracketStart ()
token leftBracesStart ()
token rightBracesStart ()
token andStart ()
token orStart ()
token xorStart ()
Public Attributes
vec< lexerState > states
token curToken
vchar curCh
vsize line
vsize col
Private Attributes
std::wistream & stream
Detailed Description
Definition at line 13 of file lexer.hpp.
Constructor & Destructor Documentation
lexer()
lexer (std::wistream & ss) explicit
Definition at line 11 of file lexer.cpp.
References lexer::getCh().
Member Function Documentation
alphaStart()
lexer::token alphaStart ()
Definition at line 94 of file lexer.cpp.
References lexer::token::boolean, lexer::col, lexer::curCh, lexer::getCh(), lexer::token::identifier, lexer::token::kAs, lexer::token::kBreak, lexer::token::kCatch, lexer::token::kClosure, lexer::token::kContinue, lexer::token::kElse, lexer::token::kFor, lexer::token::kForEach, lexer::token::kFunc, lexer::token::kIf, lexer::token::kIn, lexer::token::kLet, lexer::token::kNull, lexer::token::kReturn, lexer::token::kThrow, lexer::token::kTry, lexer::token::kWhile, lexer::token::kWith, and lexer::line.
Referenced by lexer::scan().
andStart()
lexer::token andStart ()
Definition at line 395 of file lexer.cpp.
References lexer::token::binaryAnd, lexer::col, lexer::curCh, lexer::getCh(), lexer::line, and lexer::token::logicAnd.
Referenced by lexer::scan().
asteriskStart()
lexer::token asteriskStart ()
Definition at line 224 of file lexer.cpp.
References lexer::token::asterisk, lexer::col, lexer::curCh, lexer::getCh(), lexer::line, and lexer::token::multiplicationAssignment.
Referenced by lexer::scan().
colonStart()
lexer::token colonStart ()
Definition at line 324 of file lexer.cpp.
References lexer::col, lexer::token::colon, lexer::getCh(), and lexer::line.
Referenced by lexer::scan().
commaStart()
lexer::token commaStart ()
Definition at line 330 of file lexer.cpp.
References lexer::col, lexer::token::comma, lexer::getCh(), and lexer::line.
Referenced by lexer::scan().
digitStart()
lexer::token digitStart ()
Definition at line 170 of file lexer.cpp.
References lexer::col, lexer::curCh, lexer::token::decimal, lexer::getCh(), lexer::token::integer, and lexer::line.
Referenced by lexer::scan().
dotStart()
lexer::token dotStart ()
Definition at line 336 of file lexer.cpp.
References lexer::col, lexer::token::dot, lexer::getCh(), and lexer::line.
Referenced by lexer::scan().
dropState()
void dropState ()
Definition at line 390 of file lexer.cpp.
References lexer::states.
Referenced by parser::parseAssignmentExpression(), parser::parseSubscriptExpression(), parser::parseUniqueExpression(), and lexer::returnState().
equalStart()
lexer::token equalStart ()
Definition at line 272 of file lexer.cpp.
References lexer::token::assignSign, lexer::col, lexer::curCh, lexer::token::equal, lexer::getCh(), and lexer::line.
Referenced by lexer::scan().
getCh()
void getCh ()
Definition at line 15 of file lexer.cpp.
References lexer::col, lexer::curCh, lexer::line, and lexer::stream.
Referenced by lexer::alphaStart(), lexer::andStart(), lexer::asteriskStart(), lexer::colonStart(), lexer::commaStart(), lexer::digitStart(), lexer::dotStart(), lexer::equalStart(), lexer::greaterStart(), lexer::leftBracesStart(), lexer::leftBracketStart(), lexer::leftParenthesesStart(), lexer::lessStart(), lexer::lexer(), lexer::minusStart(), lexer::notStart(), lexer::orStart(), lexer::percentSignStart(), lexer::plusStart(), lexer::rightBracesStart(), lexer::rightBracketStart(), lexer::rightParenthesesStart(), lexer::scan(), lexer::semicolonStart(), lexer::slashStart(), lexer::strStart(), and lexer::xorStart().
greaterStart()
lexer::token greaterStart ()
Definition at line 305 of file lexer.cpp.
References lexer::token::binaryShiftRight, lexer::col, lexer::curCh, lexer::getCh(), lexer::token::greaterEqual, lexer::token::greaterThan, and lexer::line.
Referenced by lexer::scan().
leftBracesStart()
lexer::token leftBracesStart ()
Definition at line 366 of file lexer.cpp.
References lexer::col, lexer::getCh(), lexer::token::leftBraces, and lexer::line.
Referenced by lexer::scan().
leftBracketStart()
lexer::token leftBracketStart ()
Definition at line 354 of file lexer.cpp.
References lexer::col, lexer::getCh(), lexer::token::leftBracket, and lexer::line.
Referenced by lexer::scan().
leftParenthesesStart()
lexer::token leftParenthesesStart ()
Definition at line 342 of file lexer.cpp.
References lexer::col, lexer::getCh(), lexer::token::leftParentheses, and lexer::line.
Referenced by lexer::scan().
lessStart()
lexer::token lessStart ()
Definition at line 292 of file lexer.cpp.
References lexer::token::binaryShiftLeft, lexer::col, lexer::curCh, lexer::getCh(), lexer::token::lessEqual, lexer::token::lessThan, and lexer::line.
Referenced by lexer::scan().
minusStart()
lexer::token minusStart ()
Definition at line 195 of file lexer.cpp.
References lexer::col, lexer::curCh, lexer::token::decrementSign, lexer::getCh(), lexer::line, lexer::token::minus, lexer::token::subtractionAssignment, and lexer::token::toSign.
Referenced by lexer::scan().
notStart()
lexer::token notStart ()
Definition at line 282 of file lexer.cpp.
References lexer::col, lexer::curCh, lexer::getCh(), lexer::line, lexer::token::logicNot, and lexer::token::notEqual.
Referenced by lexer::scan().
orStart()
lexer::token orStart ()
Definition at line 405 of file lexer.cpp.
References lexer::token::binaryOr, lexer::col, lexer::curCh, lexer::getCh(), lexer::line, and lexer::token::logicOr.
Referenced by lexer::scan().
percentSignStart()
lexer::token percentSignStart ()
Definition at line 262 of file lexer.cpp.
References lexer::col, lexer::curCh, lexer::getCh(), lexer::line, lexer::token::percentSign, and lexer::token::reminderAssignment.
Referenced by lexer::scan().
plusStart()
lexer::token plusStart ()
Definition at line 211 of file lexer.cpp.
References lexer::token::additionAssignment, lexer::col, lexer::curCh, lexer::getCh(), lexer::token::incrementSign, lexer::line, and lexer::token::plus.
Referenced by lexer::scan().
returnState()
void returnState ()
Definition at line 382 of file lexer.cpp.
References lexer::lexerState::col, lexer::col, lexer::lexerState::curCh, lexer::curCh, lexer::lexerState::curToken, lexer::curToken, lexer::dropState(), lexer::lexerState::line, lexer::line, lexer::lexerState::pos, lexer::states, and lexer::stream.
Referenced by parser::parseAssignmentExpression(), parser::parseSubscriptExpression(), and parser::parseUniqueExpression().
rightBracesStart()
lexer::token rightBracesStart ()
Definition at line 372 of file lexer.cpp.
References lexer::col, lexer::getCh(), lexer::line, and lexer::token::rightBraces.
Referenced by lexer::scan().
rightBracketStart()
lexer::token rightBracketStart ()
Definition at line 360 of file lexer.cpp.
References lexer::col, lexer::getCh(), lexer::line, and lexer::token::rightBracket.
Referenced by lexer::scan().
rightParenthesesStart()
lexer::token rightParenthesesStart ()
Definition at line 348 of file lexer.cpp.
References lexer::col, lexer::getCh(), lexer::line, and lexer::token::rightParentheses.
Referenced by lexer::scan().
saveState()
void saveState ()
Definition at line 378 of file lexer.cpp.
References lexer::col, lexer::curCh, lexer::curToken, lexer::line, lexer::states, and lexer::stream.
Referenced by parser::parseAssignmentExpression(), parser::parseSubscriptExpression(), and parser::parseUniqueExpression().
scan()
lexer::token scan ()
Definition at line 32 of file lexer.cpp.
References lexer::alphaStart(), lexer::andStart(), lexer::asteriskStart(), lexer::col, lexer::colonStart(), lexer::commaStart(), lexer::curCh, lexer::curToken, lexer::digitStart(), lexer::dotStart(), lexer::token::eof, lexer::equalStart(), lexer::getCh(), lexer::greaterStart(), lexer::leftBracesStart(), lexer::leftBracketStart(), lexer::leftParenthesesStart(), lexer::lessStart(), lexer::line, lexer::minusStart(), lexer::notStart(), lexer::orStart(), lexer::percentSignStart(), lexer::plusStart(), lexer::rightBracesStart(), lexer::rightBracketStart(), lexer::rightParenthesesStart(), lexer::semicolonStart(), lexer::slashStart(), lexer::strStart(), and lexer::xorStart().
Referenced by parser::parseAdditionExpression(), parser::parseArguments(), parser::parseAssignmentExpression(), parser::parseBasicLiterals(), parser::parseBinaryExpression(), parser::parseBinaryShiftExpression(), parser::parseBlockStmt(), parser::parseBreakStmt(), parser::parseClosureDefinition(), parser::parseContinueStmt(), parser::parseFile(), parser::parseForStmt(), parser::parseFunctionDefinition(), parser::parseFunctionDefStmt(), parser::parseIdentifier(), parser::parseIfStmt(), parser::parseLetStmt(), parser::parseListLiteral(), parser::parseLogicAndExpression(), parser::parseLogicEqualExpression(), parser::parseMemberExpression(), parser::parseMultiplicationExpression(), parser::parseObjectLiteral(), parser::parsePrimary(), parser::parser(), parser::parseRangeBasedForStmt(), parser::parseReturnStmt(), parser::parseSubscriptExpression(), parser::parseThrowStmt(), parser::parseTryCatchStmt(), parser::parseUniqueExpression(), parser::parseWhileStmt(), parser::parseWithStmt(), and lexer::slashStart().
semicolonStart()
lexer::token semicolonStart ()
Definition at line 318 of file lexer.cpp.
References lexer::col, lexer::getCh(), lexer::line, and lexer::token::semicolon.
Referenced by lexer::scan().
slashStart()
lexer::token slashStart ()
Definition at line 234 of file lexer.cpp.
References lexer::col, lexer::curCh, lexer::token::divisionAssignment, lexer::getCh(), lexer::line, lexer::scan(), and lexer::token::slash.
Referenced by lexer::scan().
strStart()
lexer::token strStart ()
Definition at line 151 of file lexer.cpp.
References lexer::col, lexer::curCh, lexer::getCh(), lexer::line, rex::parseString(), and lexer::token::string.
Referenced by lexer::scan().
xorStart()
lexer::token xorStart ()
Definition at line 415 of file lexer.cpp.
References lexer::token::binaryXor, lexer::col, lexer::getCh(), and lexer::line.
Referenced by lexer::scan().
Member Data Documentation
col
vsize col
Definition at line 124 of file lexer.hpp.
Referenced by lexer::alphaStart(), lexer::andStart(), lexer::asteriskStart(), lexer::colonStart(), lexer::commaStart(), lexer::digitStart(), lexer::dotStart(), lexer::equalStart(), lexer::getCh(), lexer::greaterStart(), lexer::leftBracesStart(), lexer::leftBracketStart(), lexer::leftParenthesesStart(), lexer::lessStart(), lexer::minusStart(), lexer::notStart(), lexer::orStart(), parser::parseAdditionExpression(), parser::parseArguments(), parser::parseAssignmentExpression(), parser::parseBinaryExpression(), parser::parseBinaryShiftExpression(), parser::parseBlockStmt(), parser::parseClosureDefinition(), parser::parseFile(), parser::parseForStmt(), parser::parseFunctionDefinition(), parser::parseFunctionDefStmt(), parser::parseIfStmt(), parser::parseLetStmt(), parser::parseListLiteral(), parser::parseLogicAndExpression(), parser::parseLogicEqualExpression(), parser::parseMemberExpression(), parser::parseMultiplicationExpression(), parser::parseObjectLiteral(), parser::parsePrimary(), parser::parseRangeBasedForStmt(), parser::parseReturnStmt(), parser::parseSubscriptExpression(), parser::parseThrowStmt(), parser::parseTryCatchStmt(), parser::parseUniqueExpression(), parser::parseWhileStmt(), parser::parseWithStmt(), lexer::percentSignStart(), lexer::plusStart(), lexer::returnState(), lexer::rightBracesStart(), lexer::rightBracketStart(), lexer::rightParenthesesStart(), lexer::saveState(), lexer::scan(), lexer::semicolonStart(), lexer::slashStart(), lexer::strStart(), and lexer::xorStart().
curCh
vchar curCh
Definition at line 122 of file lexer.hpp.
Referenced by lexer::alphaStart(), lexer::andStart(), lexer::asteriskStart(), lexer::digitStart(), lexer::equalStart(), lexer::getCh(), lexer::greaterStart(), lexer::lessStart(), lexer::minusStart(), lexer::notStart(), lexer::orStart(), lexer::percentSignStart(), lexer::plusStart(), lexer::returnState(), lexer::saveState(), lexer::scan(), lexer::slashStart(), and lexer::strStart().
curToken
token curToken
Definition at line 121 of file lexer.hpp.
Referenced by parser::parseAdditionExpression(), parser::parseArguments(), parser::parseAssignmentExpression(), parser::parseBasicLiterals(), parser::parseBinaryExpression(), parser::parseBinaryShiftExpression(), parser::parseBlockStmt(), parser::parseBreakStmt(), parser::parseClosureDefinition(), parser::parseContinueStmt(), parser::parseFile(), parser::parseForStmt(), parser::parseFunctionDefinition(), parser::parseFunctionDefStmt(), parser::parseIdentifier(), parser::parseIfStmt(), parser::parseLetStmt(), parser::parseListLiteral(), parser::parseLogicAndExpression(), parser::parseLogicEqualExpression(), parser::parseMemberExpression(), parser::parseMultiplicationExpression(), parser::parseObjectLiteral(), parser::parsePrimary(), parser::parseRangeBasedForStmt(), parser::parseReturnStmt(), parser::parseSubscriptExpression(), parser::parseThrowStmt(), parser::parseTryCatchStmt(), parser::parseUniqueExpression(), parser::parseWhileStmt(), parser::parseWithStmt(), lexer::returnState(), lexer::saveState(), and lexer::scan().
line
vsize line
Definition at line 124 of file lexer.hpp.
Referenced by lexer::alphaStart(), lexer::andStart(), lexer::asteriskStart(), lexer::colonStart(), lexer::commaStart(), lexer::digitStart(), lexer::dotStart(), lexer::equalStart(), lexer::getCh(), lexer::greaterStart(), lexer::leftBracesStart(), lexer::leftBracketStart(), lexer::leftParenthesesStart(), lexer::lessStart(), lexer::minusStart(), lexer::notStart(), lexer::orStart(), parser::parseAdditionExpression(), parser::parseArguments(), parser::parseAssignmentExpression(), parser::parseBinaryExpression(), parser::parseBinaryShiftExpression(), parser::parseBlockStmt(), parser::parseClosureDefinition(), parser::parseFile(), parser::parseForStmt(), parser::parseFunctionDefinition(), parser::parseFunctionDefStmt(), parser::parseIfStmt(), parser::parseLetStmt(), parser::parseListLiteral(), parser::parseLogicAndExpression(), parser::parseLogicEqualExpression(), parser::parseMemberExpression(), parser::parseMultiplicationExpression(), parser::parseObjectLiteral(), parser::parsePrimary(), parser::parseRangeBasedForStmt(), parser::parseReturnStmt(), parser::parseSubscriptExpression(), parser::parseThrowStmt(), parser::parseTryCatchStmt(), parser::parseUniqueExpression(), parser::parseWhileStmt(), parser::parseWithStmt(), lexer::percentSignStart(), lexer::plusStart(), lexer::returnState(), lexer::rightBracesStart(), lexer::rightBracketStart(), lexer::rightParenthesesStart(), lexer::saveState(), lexer::scan(), lexer::semicolonStart(), lexer::slashStart(), lexer::strStart(), and lexer::xorStart().
states
vec<lexerState> states
Definition at line 119 of file lexer.hpp.
Referenced by lexer::dropState(), lexer::returnState(), and lexer::saveState().
stream
std::wistream& stream private
Definition at line 14 of file lexer.hpp.
Referenced by lexer::getCh(), lexer::returnState(), and lexer::saveState().
The documentation for this class was generated from the following files:
frontend/lexer.hpp
frontend/lexer.cpp