reXscript: signalException Class Reference
signalException Class Reference
#include <signalException.hpp>
Public Member Functions
signalException (const value &v)
value & get ()
Private Attributes
value msg
Additional Inherited Members
Private Member Functions inherited from interpreterSignal
interpreterSignal ()
const char * what () const noexcept override
Detailed Description
Definition at line 13 of file signalException.hpp.
Constructor & Destructor Documentation
signalException()
signalException (const value & v)
Definition at line 10 of file signalException.cpp.
Member Function Documentation
get()
value & get ()
Definition at line 14 of file signalException.cpp.
References signalException::msg.
Referenced by interactiveShell(), interpreter::interpret(), rex::bytecodeEngine::requireModule(), rex::bytecodeEngine::requireNativeModule(), rex::bytecodeEngine::requirePackage(), and rex::bytecodeEngine::rexThreadWrapper().
Member Data Documentation
msg
value msg private
Definition at line 14 of file signalException.hpp.
Referenced by signalException::get().
The documentation for this class was generated from the following files:
exceptions/signalException.hpp
exceptions/signalException.cpp