reXscript: interpreterSignal Class Reference
interpreterSignal Class Reference
#include <interpreterSignal.hpp>
Public Member Functions
interpreterSignal ()
const char * what () const noexcept override
Detailed Description
Definition at line 12 of file interpreterSignal.hpp.
Constructor & Destructor Documentation
interpreterSignal()
interpreterSignal ()
Definition at line 8 of file interpreterSignal.cpp.
Member Function Documentation
what()
const char * what () const override noexcept
Definition at line 12 of file interpreterSignal.cpp.
Referenced by interactiveShell(), rex::bytecodeEngine::requireModule(), rex::bytecodeEngine::requireNativeModule(), rex::bytecodeEngine::requirePackage(), and rex::bytecodeEngine::rexThreadWrapper().
The documentation for this class was generated from the following files:
exceptions/interpreterSignal.hpp
exceptions/interpreterSignal.cpp