reXscript: codeBuilder Class Reference
codeBuilder Class Reference
#include <bytecodeEngine.hpp>
Public Member Functions
codeBuilder (bytecodeModule mod, codeStruct &currentBlock)
uint64_t getNextCur ()
void buildBasicLiterals (const AST &target)
void buildIdentifier (const AST &target)
void buildSubscriptExpr (const AST &target)
void buildInvokeExpr (const AST &target)
void buildListLiteral (const AST &target)
void buildObjectLiteral (const AST &target)
void buildLambdaDef (const AST &target)
void buildFuncDef (const AST &target)
void buildMemberExpr (const AST &target)
void buildUniqueExpr (const AST &target)
void buildMulExpr (const AST &target)
void buildAddExpr (const AST &target)
void buildBinShiftExpr (const AST &target)
void buildLogicEqExpr (const AST &target)
void buildBinExpr (const AST &target)
void buildLogicAndExpr (const AST &target)
void buildAssignmentExpr (const AST &target)
void buildBlockStmt (const AST &target)
void buildLetStmt (const AST &target)
void buildWhileStmt (const AST &target)
void buildForStmt (const AST &target)
void buildForEachStmt (const AST &target)
void buildIfStmt (const AST &target)
void buildIfElseStmt (const AST &target)
void buildReturnStmt (const AST &target)
void buildContinueStmt (const AST &target)
void buildBreakStmt (const AST &target)
void buildTryCatchStmt (const AST &target)
void buildThrowStmt (const AST &target)
void buildFuncDefStmt (const AST &target)
void buildStmt (const AST &target)
void buildExpr (const AST &target)
Private Attributes
bytecodeModule mod
codeStruct & currentBlock
Detailed Description
Definition at line 126 of file bytecodeEngine.hpp.
Constructor & Destructor Documentation
codeBuilder()
codeBuilder (bytecodeModule mod, codeStruct & currentBlock)
Definition at line 306 of file bytecodeEngine.cpp.
Member Function Documentation
buildAddExpr()
void buildAddExpr (const AST & target)
Definition at line 474 of file bytecodeEngine.cpp.
References codeBuilder::buildExpr(), AST::child, codeStruct::code, codeBuilder::currentBlock, lexer::token::minus, bytecodeStruct::opAdd, bytecodeStruct::opSub, and lexer::token::plus.
Referenced by codeBuilder::buildExpr().
buildAssignmentExpr()
void buildAssignmentExpr (const AST & target)
Definition at line 569 of file bytecodeEngine.cpp.
References bytecodeStruct::addAssign, lexer::token::additionAssignment, bytecodeStruct::assign, lexer::token::assignSign, codeBuilder::buildExpr(), AST::child, codeStruct::code, codeBuilder::currentBlock, bytecodeStruct::divAssign, lexer::token::divisionAssignment, bytecodeStruct::modAssign, bytecodeStruct::mulAssign, lexer::token::multiplicationAssignment, lexer::token::reminderAssignment, bytecodeStruct::subAssign, and lexer::token::subtractionAssignment.
Referenced by codeBuilder::buildStmt().
buildBasicLiterals()
void buildBasicLiterals (const AST & target)
Definition at line 315 of file bytecodeEngine.cpp.
References lexer::token::basicVal, bytecodeStruct::boolConst, lexer::token::boolean, codeStruct::code, codeBuilder::currentBlock, bytecodeStruct::deciConst, lexer::token::decimal, bytecodeStruct::intConst, lexer::token::integer, lexer::token::kind, lexer::token::kNull, AST::leaf, bytecodeStruct::nullConst, codeStruct::putStringConst(), lexer::token::string, bytecodeStruct::stringNew, lexer::token::strVal, lexer::token::vBasicValue::vBool, lexer::token::vBasicValue::vDeci, and lexer::token::vBasicValue::vInt.
Referenced by codeBuilder::buildExpr().
buildBinExpr()
void buildBinExpr (const AST & target)
Definition at line 534 of file bytecodeEngine.cpp.
References lexer::token::binaryAnd, lexer::token::binaryOr, lexer::token::binaryXor, codeBuilder::buildExpr(), AST::child, codeStruct::code, codeBuilder::currentBlock, bytecodeStruct::opBinaryAnd, bytecodeStruct::opBinaryOr, and bytecodeStruct::opBinaryXor.
Referenced by codeBuilder::buildExpr().
buildBinShiftExpr()
void buildBinShiftExpr (const AST & target)
Definition at line 490 of file bytecodeEngine.cpp.
References lexer::token::binaryShiftLeft, lexer::token::binaryShiftRight, codeBuilder::buildExpr(), AST::child, codeStruct::code, codeBuilder::currentBlock, bytecodeStruct::opBinaryShiftLeft, and bytecodeStruct::opBinaryShiftRight.
Referenced by codeBuilder::buildExpr().
buildBlockStmt()
void buildBlockStmt (const AST & target)
Definition at line 596 of file bytecodeEngine.cpp.
References AST::child, codeStruct::code, codeBuilder::currentBlock, bytecodeStruct::popLocalCxt, and bytecodeStruct::pushLocalCxt.
Referenced by codeBuilder::buildStmt().
buildBreakStmt()
void buildBreakStmt (const AST & target)
Definition at line 730 of file bytecodeEngine.cpp.
References codeStruct::code, codeBuilder::currentBlock, bytecodeStruct::fakeOpBreak, and bytecodeStruct::popLocalCxt.
Referenced by codeBuilder::buildStmt().
buildContinueStmt()
void buildContinueStmt (const AST & target)
Definition at line 725 of file bytecodeEngine.cpp.
References codeStruct::code, codeBuilder::currentBlock, bytecodeStruct::fakeOpContinue, and bytecodeStruct::popLocalCxt.
Referenced by codeBuilder::buildStmt().
buildExpr()
void buildExpr (const AST & target)
Definition at line 842 of file bytecodeEngine.cpp.
References AST::additionExpression, AST::basicLiterals, AST::binaryExpression, AST::binaryShiftExpression, codeBuilder::buildAddExpr(), codeBuilder::buildBasicLiterals(), codeBuilder::buildBinExpr(), codeBuilder::buildBinShiftExpr(), codeBuilder::buildFuncDef(), codeBuilder::buildIdentifier(), codeBuilder::buildInvokeExpr(), codeBuilder::buildLambdaDef(), codeBuilder::buildListLiteral(), codeBuilder::buildLogicAndExpr(), codeBuilder::buildLogicEqExpr(), codeBuilder::buildMemberExpr(), codeBuilder::buildMulExpr(), codeBuilder::buildObjectLiteral(), codeBuilder::buildSubscriptExpr(), codeBuilder::buildUniqueExpr(), AST::functionDefinition, AST::identifier, AST::invokingExpression, AST::kind, AST::lambdaDefinition, AST::listLiteral, AST::logicAndExpression, AST::logicEqualExpression, AST::memberExpression, AST::multiplicationExpression, AST::objectLiteral, AST::subscriptExpression, and AST::uniqueExpression.
Referenced by codeBuilder::buildAddExpr(), codeBuilder::buildAssignmentExpr(), codeBuilder::buildBinExpr(), codeBuilder::buildBinShiftExpr(), codeBuilder::buildForEachStmt(), codeBuilder::buildForStmt(), codeBuilder::buildIfElseStmt(), codeBuilder::buildIfStmt(), codeBuilder::buildInvokeExpr(), codeBuilder::buildLogicAndExpr(), codeBuilder::buildLogicEqExpr(), codeBuilder::buildMemberExpr(), codeBuilder::buildMulExpr(), codeBuilder::buildObjectLiteral(), codeBuilder::buildReturnStmt(), codeBuilder::buildStmt(), codeBuilder::buildSubscriptExpr(), codeBuilder::buildThrowStmt(), codeBuilder::buildUniqueExpr(), and codeBuilder::buildWhileStmt().
buildForEachStmt()
void buildForEachStmt (const AST & target)
Definition at line 663 of file bytecodeEngine.cpp.
References codeBuilder::buildExpr(), codeBuilder::buildStmt(), AST::child, codeStruct::code, bytecodeStruct::createOrAssign, codeBuilder::currentBlock, bytecodeStruct::duplicate, bytecodeStruct::fakeOpBreak, bytecodeStruct::fakeOpContinue, bytecodeStruct::findAttr, bytecodeStruct::forEach, codeBuilder::getNextCur(), bytecodeStruct::invokeMethod, bytecodeStruct::jump, bytecodeStruct::popLocalCxt, bytecodeStruct::popTop, bytecodeStruct::pushLocalCxt, and codeStruct::putNames().
Referenced by codeBuilder::buildStmt().
buildForStmt()
void buildForStmt (const AST & target)
Definition at line 632 of file bytecodeEngine.cpp.
References codeBuilder::buildExpr(), codeBuilder::buildStmt(), AST::child, codeStruct::code, codeBuilder::currentBlock, bytecodeStruct::fakeOpContinue, codeBuilder::getNextCur(), bytecodeStruct::jump, bytecodeStruct::jumpIfFalse, bytecodeStruct::popLocalCxt, and bytecodeStruct::pushLocalCxt.
Referenced by codeBuilder::buildStmt().
buildFuncDef()
void buildFuncDef (const AST & target)
Definition at line 392 of file bytecodeEngine.cpp.
References AST::child.
Referenced by codeBuilder::buildExpr().
buildFuncDefStmt()
void buildFuncDefStmt (const AST & target)
Definition at line 761 of file bytecodeEngine.cpp.
References AST::child.
Referenced by codeBuilder::buildStmt().
buildIdentifier()
void buildIdentifier (const AST & target)
Definition at line 338 of file bytecodeEngine.cpp.
References codeStruct::code, codeBuilder::currentBlock, bytecodeStruct::find, AST::leaf, codeStruct::putNames(), and lexer::token::strVal.
Referenced by codeBuilder::buildExpr().
buildIfElseStmt()
void buildIfElseStmt (const AST & target)
Definition at line 705 of file bytecodeEngine.cpp.
References codeBuilder::buildExpr(), codeBuilder::buildStmt(), AST::child, codeStruct::code, codeBuilder::currentBlock, codeBuilder::getNextCur(), bytecodeStruct::jump, and bytecodeStruct::jumpIfFalse.
Referenced by codeBuilder::buildStmt().
buildIfStmt()
void buildIfStmt (const AST & target)
Definition at line 696 of file bytecodeEngine.cpp.
References codeBuilder::buildExpr(), codeBuilder::buildStmt(), AST::child, codeStruct::code, codeBuilder::currentBlock, codeBuilder::getNextCur(), and bytecodeStruct::jumpIfFalse.
Referenced by codeBuilder::buildStmt().
buildInvokeExpr()
void buildInvokeExpr (const AST & target)
Definition at line 348 of file bytecodeEngine.cpp.
References codeBuilder::buildExpr(), AST::child, codeStruct::code, codeBuilder::currentBlock, and bytecodeStruct::invoke.
Referenced by codeBuilder::buildExpr().
buildLambdaDef()
void buildLambdaDef (const AST & target)
Definition at line 372 of file bytecodeEngine.cpp.
References AST::child, codeStruct::code, codeBuilder::currentBlock, bytecodeStruct::find, AST::leaf, codeStruct::putNames(), and lexer::token::strVal.
Referenced by codeBuilder::buildExpr().
buildLetStmt()
void buildLetStmt (const AST & target)
Definition at line 604 of file bytecodeEngine.cpp.
References AST::child.
Referenced by codeBuilder::buildStmt().
buildListLiteral()
void buildListLiteral (const AST & target)
Definition at line 356 of file bytecodeEngine.cpp.
References bytecodeStruct::arrayNew, AST::child, codeStruct::code, and codeBuilder::currentBlock.
Referenced by codeBuilder::buildExpr().
buildLogicAndExpr()
void buildLogicAndExpr (const AST & target)
Definition at line 553 of file bytecodeEngine.cpp.
References codeBuilder::buildExpr(), AST::child, codeStruct::code, codeBuilder::currentBlock, lexer::token::logicAnd, lexer::token::logicOr, bytecodeStruct::opLogicAnd, and bytecodeStruct::opLogicOr.
Referenced by codeBuilder::buildExpr().
buildLogicEqExpr()
void buildLogicEqExpr (const AST & target)
Definition at line 506 of file bytecodeEngine.cpp.
References codeBuilder::buildExpr(), AST::child, codeStruct::code, codeBuilder::currentBlock, lexer::token::equal, lexer::token::greaterEqual, lexer::token::greaterThan, lexer::token::lessEqual, lexer::token::lessThan, lexer::token::notEqual, bytecodeStruct::opEqual, bytecodeStruct::opGreaterEqual, bytecodeStruct::opGreaterThan, bytecodeStruct::opLessEqual, bytecodeStruct::opLessThan, and bytecodeStruct::opNotEqual.
Referenced by codeBuilder::buildExpr().
buildMemberExpr()
void buildMemberExpr (const AST & target)
Definition at line 404 of file bytecodeEngine.cpp.
References codeBuilder::buildExpr(), AST::child, codeStruct::code, codeBuilder::currentBlock, bytecodeStruct::duplicate, bytecodeStruct::findAttr, AST::identifier, bytecodeStruct::index, bytecodeStruct::invokeMethod, AST::invokingExpression, codeStruct::putNames(), and AST::subscriptExpression.
Referenced by codeBuilder::buildExpr().
buildMulExpr()
void buildMulExpr (const AST & target)
Definition at line 455 of file bytecodeEngine.cpp.
References lexer::token::asterisk, codeBuilder::buildExpr(), AST::child, codeStruct::code, codeBuilder::currentBlock, bytecodeStruct::opDiv, bytecodeStruct::opMod, bytecodeStruct::opMul, lexer::token::percentSign, and lexer::token::slash.
Referenced by codeBuilder::buildExpr().
buildObjectLiteral()
void buildObjectLiteral (const AST & target)
Definition at line 363 of file bytecodeEngine.cpp.
References codeBuilder::buildExpr(), and AST::child.
Referenced by codeBuilder::buildExpr().
buildReturnStmt()
void buildReturnStmt (const AST & target)
Definition at line 720 of file bytecodeEngine.cpp.
References codeBuilder::buildExpr(), AST::child, codeStruct::code, codeBuilder::currentBlock, and bytecodeStruct::ret.
Referenced by codeBuilder::buildStmt().
buildStmt()
void buildStmt (const AST & target)
Definition at line 772 of file bytecodeEngine.cpp.
References AST::additionExpression, AST::assignmentExpression, AST::binaryExpression, AST::binaryShiftExpression, AST::blockStmt, AST::breakStmt, codeBuilder::buildAssignmentExpr(), codeBuilder::buildBlockStmt(), codeBuilder::buildBreakStmt(), codeBuilder::buildContinueStmt(), codeBuilder::buildExpr(), codeBuilder::buildForEachStmt(), codeBuilder::buildForStmt(), codeBuilder::buildFuncDefStmt(), codeBuilder::buildIfElseStmt(), codeBuilder::buildIfStmt(), codeBuilder::buildLetStmt(), codeBuilder::buildReturnStmt(), codeBuilder::buildThrowStmt(), codeBuilder::buildTryCatchStmt(), codeBuilder::buildWhileStmt(), codeStruct::code, lexer::token::col, runtimeSourceFileMsg::col, AST::continueStmt, codeBuilder::currentBlock, AST::forStmt, AST::functionDefinition, AST::functionDefStmt, AST::identifier, AST::ifElseStmt, AST::ifStmt, AST::invokingExpression, AST::kind, AST::lambdaDefinition, AST::leaf, AST::letStmt, lexer::token::line, runtimeSourceFileMsg::line, AST::listLiteral, AST::logicAndExpression, AST::logicEqualExpression, AST::memberExpression, codeStruct::msg, AST::multiplicationExpression, AST::objectLiteral, bytecodeStruct::popTop, AST::rangeBasedForStmt, AST::returnStmt, AST::subscriptExpression, AST::throwStmt, AST::tryCatchStmt, AST::uniqueExpression, and AST::whileStmt.
Referenced by codeBuilder::buildForEachStmt(), codeBuilder::buildForStmt(), codeBuilder::buildIfElseStmt(), codeBuilder::buildIfStmt(), codeBuilder::buildTryCatchStmt(), codeBuilder::buildWhileStmt(), rex::bytecodeEngine::compile(), dis(), and interactiveShell().
buildSubscriptExpr()
void buildSubscriptExpr (const AST & target)
Definition at line 342 of file bytecodeEngine.cpp.
References codeBuilder::buildExpr(), AST::child, codeStruct::code, codeBuilder::currentBlock, and bytecodeStruct::index.
Referenced by codeBuilder::buildExpr().
buildThrowStmt()
void buildThrowStmt (const AST & target)
Definition at line 756 of file bytecodeEngine.cpp.
References codeBuilder::buildExpr(), AST::child, codeStruct::code, codeBuilder::currentBlock, and bytecodeStruct::opThrow.
Referenced by codeBuilder::buildStmt().
buildTryCatchStmt()
void buildTryCatchStmt (const AST & target)
Definition at line 735 of file bytecodeEngine.cpp.
References codeBuilder::buildStmt(), AST::child, codeStruct::code, bytecodeStruct::createOrAssign, codeBuilder::currentBlock, codeBuilder::getNextCur(), bytecodeStruct::jump, bytecodeStruct::popExceptionHandler, bytecodeStruct::popLocalCxt, bytecodeStruct::pushExceptionHandler, bytecodeStruct::pushLocalCxt, and codeStruct::putNames().
Referenced by codeBuilder::buildStmt().
buildUniqueExpr()
void buildUniqueExpr (const AST & target)
Definition at line 435 of file bytecodeEngine.cpp.
References lexer::token::asterisk, codeBuilder::buildExpr(), AST::child, codeStruct::code, codeBuilder::currentBlock, lexer::token::decrementSign, bytecodeStruct::deepCopy, lexer::token::incrementSign, lexer::token::minus, bytecodeStruct::opDecrement, bytecodeStruct::opIncrement, and bytecodeStruct::opNegate.
Referenced by codeBuilder::buildExpr().
buildWhileStmt()
void buildWhileStmt (const AST & target)
Definition at line 612 of file bytecodeEngine.cpp.
References codeBuilder::buildExpr(), codeBuilder::buildStmt(), AST::child, codeStruct::code, codeBuilder::currentBlock, bytecodeStruct::fakeOpContinue, codeBuilder::getNextCur(), bytecodeStruct::jump, and bytecodeStruct::jumpIfFalse.
Referenced by codeBuilder::buildStmt().
getNextCur()
uint64_t getNextCur ()
Definition at line 311 of file bytecodeEngine.cpp.
References codeStruct::code, and codeBuilder::currentBlock.
Referenced by codeBuilder::buildForEachStmt(), codeBuilder::buildForStmt(), codeBuilder::buildIfElseStmt(), codeBuilder::buildIfStmt(), codeBuilder::buildTryCatchStmt(), and codeBuilder::buildWhileStmt().
Member Data Documentation
currentBlock
codeStruct& currentBlock private
Definition at line 128 of file bytecodeEngine.hpp.
Referenced by codeBuilder::buildAddExpr(), codeBuilder::buildAssignmentExpr(), codeBuilder::buildBasicLiterals(), codeBuilder::buildBinExpr(), codeBuilder::buildBinShiftExpr(), codeBuilder::buildBlockStmt(), codeBuilder::buildBreakStmt(), codeBuilder::buildContinueStmt(), codeBuilder::buildForEachStmt(), codeBuilder::buildForStmt(), codeBuilder::buildIdentifier(), codeBuilder::buildIfElseStmt(), codeBuilder::buildIfStmt(), codeBuilder::buildInvokeExpr(), codeBuilder::buildLambdaDef(), codeBuilder::buildListLiteral(), codeBuilder::buildLogicAndExpr(), codeBuilder::buildLogicEqExpr(), codeBuilder::buildMemberExpr(), codeBuilder::buildMulExpr(), codeBuilder::buildReturnStmt(), codeBuilder::buildStmt(), codeBuilder::buildSubscriptExpr(), codeBuilder::buildThrowStmt(), codeBuilder::buildTryCatchStmt(), codeBuilder::buildUniqueExpr(), codeBuilder::buildWhileStmt(), and codeBuilder::getNextCur().
mod
bytecodeModule mod private
Definition at line 127 of file bytecodeEngine.hpp.
The documentation for this class was generated from the following files:
interpreter/bytecodeEngine.hpp
interpreter/bytecodeEngine.cpp