reXscript: interpreter Class Reference
interpreter Class Reference
#include <bytecodeEngine.hpp>
Classes
struct state
Public Member Functions
value invokeFunc (const managedPtr< value > &func, const vec< value > &args, const managedPtr< value > &passThisPtr)
ABI interface for native functions.
void execute (bytecodeStruct &op)
void interpret ()
interpreter ()=default
interpreter (const managedPtr< environment > &env, value::cxtObject interpreterCxt, const managedPtr< value > &moduleCxt)
vstr getBacktrace ()
void restoreState (const state &s)
bytecodeModule getBytecodeModule ()
void prepareForFuncInvoke (const managedPtr< value > &func, uint64_t argc)
prepare for the function call stack frame
void prepareForMethodInvoke (const managedPtr< value > &func, uint64_t argc)
void prepareForLambdaInvoke (const managedPtr< value > &func, uint64_t argc)
void prepareForLambdaMethodInvoke (const managedPtr< value > &func, uint64_t argc)
value invokeNativeFn (const managedPtr< value > &func, uint64_t argc)
value invokeNativeFn (const managedPtr< value > &func, const vec< value > &args, const managedPtr< value > &passThisPtr)
value invokeNativeMethod (const managedPtr< value > &func, uint64_t argc)
value opAdd (value &a, value &b)
value opSub (value &a, value &b)
value opMul (value &a, value &b)
value opDiv (value &a, value &b)
value opMod (value &a, value &b)
value opBinaryShiftLeft (value &a, value &b)
value opBinaryShiftRight (value &a, value &b)
value opEqual (value &a, value &b)
value opNotEqual (value &a, value &b)
value opGreaterEqual (value &a, value &b)
value opLessEqual (value &a, value &b)
value opGreaterThan (value &a, value &b)
value opLessThan (value &a, value &b)
value opBinaryOr (value &a, value &b)
value opBinaryAnd (value &a, value &b)
value opBinaryXor (value &a, value &b)
value opLogicAnd (value &a, value &b)
value opLogicOr (value &a, value &b)
value opIncrement (const managedPtr< value > &ptr)
value opDecrement (const managedPtr< value > &ptr)
value opNegate (value &a)
value opAssign (const managedPtr< value > &ptr, value &a)
value opAddAssign (const managedPtr< value > &ptr, value &a)
value opSubAssign (const managedPtr< value > &ptr, value &a)
value opMulAssign (const managedPtr< value > &ptr, value &a)
value opDivAssign (const managedPtr< value > &ptr, value &a)
value opModAssign (const managedPtr< value > &ptr, value &a)
value opIndex (const managedPtr< value > &ptr, value &a)
Static Public Member Functions
static void throwErr (const value &err)
throw error in native functions
static value makeErr (const vstr &errName, const vstr &errMsg)
static value makeIt (const managedPtr< value > &left, bool isEnd)
Public Attributes
managedPtr< environment > env
vec< environment::stackFrame > callStack
value::cxtObject interpreterCxt
managedPtr< value > moduleCxt
vec< value > evalStack
vec< state > exceptionHandlers
Detailed Description
Definition at line 199 of file bytecodeEngine.hpp.
Constructor & Destructor Documentation
interpreter() [1/2]
interpreter () default
interpreter() [2/2]
interpreter (const managedPtr< environment > & env, value::cxtObject interpreterCxt, const managedPtr< value > & moduleCxt)
Definition at line 985 of file bytecodeEngine.cpp.
References interpreter::callStack, and interpreter::moduleCxt.
Member Function Documentation
execute()
void execute (bytecodeStruct & op)
Definition at line 1745 of file bytecodeEngine.cpp.
References bytecodeStruct::addAssign, bytecodeStruct::arrayNew, bytecodeStruct::assign, bytecodeStruct::boolConst, bytecodeStruct::opArgs::boolv, interpreter::callStack, bytecodeModule::codeStructs, bytecodeStruct::createOrAssign, bytecodeStruct::deciConst, bytecodeStruct::opArgs::deciv, bytecodeStruct::deepCopy, value::deepCopy(), bytecodeStruct::divAssign, bytecodeStruct::duplicate, eleGetRef, eleRefObj, interpreter::env, interpreter::evalStack, interpreter::exceptionHandlers, bytecodeStruct::find, bytecodeStruct::findAttr, bytecodeStruct::forEach, value::lambdaObject::func, bytecodeStruct::funcNew, interpreter::getBytecodeModule(), rex::stringMethods::getMethodsCxt(), rex::vecMethods::getMethodsCxt(), bytecodeStruct::index, bytecodeStruct::opArgs::indexv, bytecodeStruct::intConst, interpreter::interpret(), interpreter::interpreterCxt, bytecodeStruct::opArgs::intv, bytecodeStruct::invoke, interpreter::invokeFunc(), bytecodeStruct::invokeMethod, interpreter::invokeNativeFn(), interpreter::invokeNativeMethod(), bytecodeStruct::jump, bytecodeStruct::jumpIfFalse, bytecodeStruct::jumpIfTrue, bytecodeStruct::lambdaNew, rex::managePtr(), value::members, bytecodeStruct::modAssign, interpreter::moduleCxt, value::funcObject::moduleCxt, bytecodeStruct::mulAssign, nextOp, bytecodeStruct::nullConst, bytecodeStruct::objectNew, interpreter::opAdd(), bytecodeStruct::opAdd, interpreter::opAddAssign(), bytecodeStruct::opargs, interpreter::opAssign(), interpreter::opBinaryAnd(), bytecodeStruct::opBinaryAnd, interpreter::opBinaryOr(), bytecodeStruct::opBinaryOr, interpreter::opBinaryShiftLeft(), bytecodeStruct::opBinaryShiftLeft, interpreter::opBinaryShiftRight(), bytecodeStruct::opBinaryShiftRight, interpreter::opBinaryXor(), bytecodeStruct::opBinaryXor, bytecodeStruct::opcode, interpreter::opDecrement(), bytecodeStruct::opDecrement, interpreter::opDiv(), bytecodeStruct::opDiv, interpreter::opDivAssign(), interpreter::opEqual(), bytecodeStruct::opEqual, interpreter::opGreaterEqual(), bytecodeStruct::opGreaterEqual, interpreter::opGreaterThan(), bytecodeStruct::opGreaterThan, interpreter::opIncrement(), bytecodeStruct::opIncrement, interpreter::opIndex(), interpreter::opLessEqual(), bytecodeStruct::opLessEqual, interpreter::opLessThan(), bytecodeStruct::opLessThan, interpreter::opLogicAnd(), bytecodeStruct::opLogicAnd, interpreter::opLogicOr(), bytecodeStruct::opLogicOr, interpreter::opMod(), bytecodeStruct::opMod, interpreter::opModAssign(), interpreter::opMul(), bytecodeStruct::opMul, interpreter::opMulAssign(), interpreter::opNegate(), bytecodeStruct::opNegate, interpreter::opNotEqual(), bytecodeStruct::opNotEqual, interpreter::opSub(), bytecodeStruct::opSub, interpreter::opSubAssign(), bytecodeStruct::opThrow, bytecodeStruct::popExceptionHandler, bytecodeStruct::popLocalCxt, bytecodeStruct::popTop, interpreter::prepareForFuncInvoke(), interpreter::prepareForLambdaInvoke(), interpreter::prepareForLambdaMethodInvoke(), interpreter::prepareForMethodInvoke(), bytecodeStruct::pushExceptionHandler, bytecodeStruct::pushLocalCxt, bytecodeStruct::putIndex, bytecodeStruct::ret, bytecodeStruct::stringNew, bytecodeStruct::subAssign, interpreter::throwErr(), value::vFunc, value::vLambda, and value::vNativeFuncPtr.
Referenced by interpreter::interpret().
getBacktrace()
vstr getBacktrace ()
Definition at line 2336 of file bytecodeEngine.cpp.
References interpreter::callStack.
Referenced by interactiveShell(), and loadFile().
getBytecodeModule()
bytecodeModule getBytecodeModule ()
Definition at line 2259 of file bytecodeEngine.cpp.
References interpreter::callStack.
Referenced by interpreter::execute().
interpret()
void interpret ()
Definition at line 1668 of file bytecodeEngine.cpp.
References interpreter::callStack, interpreter::evalStack, interpreter::exceptionHandlers, interpreter::execute(), signalException::get(), and interpreter::restoreState().
Referenced by interpreter::execute(), interactiveShell(), and interpreter::invokeFunc().
invokeFunc()
value invokeFunc (const managedPtr< value > & func, const vec< value > & args, const managedPtr< value > & passThisPtr)
ABI interface for native functions.
Warning
THIS FUNCTION WILL BREAK THE SIGNLE-INTERPRET-FUNCTION RULE, ONLY FOR FORIGN INTERFACES
Definition at line 1690 of file bytecodeEngine.cpp.
References interpreter::evalStack, interpreter::interpret(), interpreter::invokeNativeFn(), interpreter::prepareForFuncInvoke(), interpreter::prepareForLambdaInvoke(), interpreter::prepareForLambdaMethodInvoke(), interpreter::prepareForMethodInvoke(), value::vFunc, value::vLambda, and value::vNativeFuncPtr.
Referenced by interpreter::execute(), interpreter::opAdd(), interpreter::opAddAssign(), interpreter::opBinaryAnd(), interpreter::opBinaryOr(), interpreter::opBinaryShiftLeft(), interpreter::opBinaryShiftRight(), interpreter::opBinaryXor(), interpreter::opDecrement(), interpreter::opDiv(), interpreter::opDivAssign(), interpreter::opEqual(), interpreter::opGreaterEqual(), interpreter::opGreaterThan(), interpreter::opIncrement(), interpreter::opIndex(), interpreter::opLessEqual(), interpreter::opLessThan(), interpreter::opLogicAnd(), interpreter::opLogicOr(), interpreter::opMod(), interpreter::opModAssign(), interpreter::opMul(), interpreter::opMulAssign(), interpreter::opNegate(), interpreter::opNotEqual(), interpreter::opSub(), and interpreter::opSubAssign().
invokeNativeFn() [1/2]
value invokeNativeFn (const managedPtr< value > & func, const vec< value > & args, const managedPtr< value > & passThisPtr)
Definition at line 2327 of file bytecodeEngine.cpp.
invokeNativeFn() [2/2]
value invokeNativeFn (const managedPtr< value > & func, uint64_t argc)
Definition at line 2302 of file bytecodeEngine.cpp.
References interpreter::evalStack.
Referenced by interpreter::execute(), interpreter::invokeFunc(), and interpreter::invokeNativeMethod().
invokeNativeMethod()
value invokeNativeMethod (const managedPtr< value > & func, uint64_t argc)
Definition at line 2314 of file bytecodeEngine.cpp.
References eleRefObj, interpreter::evalStack, and interpreter::invokeNativeFn().
Referenced by interpreter::execute().
makeErr()
value makeErr (const vstr & errName, const vstr & errMsg) static
Definition at line 1661 of file bytecodeEngine.cpp.
Referenced by rex::nativeFn().
makeIt()
value makeIt (const managedPtr< value > & left, bool isEnd) static
Definition at line 2332 of file bytecodeEngine.cpp.
References rex::vecMethods::getMethodsCxt(), and rex::managePtr().
Referenced by rex::nativeFn().
opAdd()
value opAdd (value & a, value & b)
Definition at line 992 of file bytecodeEngine.cpp.
References value::getBool(), value::getDeci(), value::getInt(), interpreter::invokeFunc(), value::kind, rex::managePtr(), value::members, valueKindComparator, value::vBool, value::vDeci, and value::vInt.
Referenced by interpreter::execute().
opAddAssign()
value opAddAssign (const managedPtr< value > & ptr, value & a)
Definition at line 1520 of file bytecodeEngine.cpp.
References value::getDeci(), value::getInt(), interpreter::invokeFunc(), value::kind, valueKindComparator, value::vDeci, and value::vInt.
Referenced by interpreter::execute().
opAssign()
value opAssign (const managedPtr< value > & ptr, value & a)
Definition at line 1515 of file bytecodeEngine.cpp.
Referenced by interpreter::execute().
opBinaryAnd()
value opBinaryAnd (value & a, value & b)
Definition at line 1372 of file bytecodeEngine.cpp.
References value::getBool(), value::getInt(), interpreter::invokeFunc(), value::kind, rex::managePtr(), value::members, valueKindComparator, value::vBool, and value::vInt.
Referenced by interpreter::execute().
opBinaryOr()
value opBinaryOr (value & a, value & b)
Definition at line 1352 of file bytecodeEngine.cpp.
References value::getBool(), value::getInt(), interpreter::invokeFunc(), value::kind, rex::managePtr(), value::members, valueKindComparator, value::vBool, and value::vInt.
Referenced by interpreter::execute().
opBinaryShiftLeft()
value opBinaryShiftLeft (value & a, value & b)
Definition at line 1132 of file bytecodeEngine.cpp.
References value::getBool(), value::getInt(), interpreter::invokeFunc(), value::kind, rex::managePtr(), value::members, valueKindComparator, value::vBool, and value::vInt.
Referenced by interpreter::execute().
opBinaryShiftRight()
value opBinaryShiftRight (value & a, value & b)
Definition at line 1152 of file bytecodeEngine.cpp.
References value::getBool(), value::getInt(), interpreter::invokeFunc(), value::kind, rex::managePtr(), value::members, valueKindComparator, value::vBool, and value::vInt.
Referenced by interpreter::execute().
opBinaryXor()
value opBinaryXor (value & a, value & b)
Definition at line 1392 of file bytecodeEngine.cpp.
References value::getBool(), value::getInt(), interpreter::invokeFunc(), value::kind, rex::managePtr(), value::members, valueKindComparator, value::vBool, and value::vInt.
Referenced by interpreter::execute().
opDecrement()
value opDecrement (const managedPtr< value > & ptr)
Definition at line 1477 of file bytecodeEngine.cpp.
References interpreter::invokeFunc(), value::vDeci, and value::vInt.
Referenced by interpreter::execute().
opDiv()
value opDiv (value & a, value & b)
Definition at line 1082 of file bytecodeEngine.cpp.
References value::getBool(), value::getDeci(), value::getInt(), interpreter::invokeFunc(), value::kind, rex::managePtr(), value::members, valueKindComparator, value::vBool, value::vDeci, and value::vInt.
Referenced by interpreter::execute().
opDivAssign()
value opDivAssign (const managedPtr< value > & ptr, value & a)
Definition at line 1604 of file bytecodeEngine.cpp.
References value::getDeci(), value::getInt(), interpreter::invokeFunc(), value::kind, valueKindComparator, value::vDeci, and value::vInt.
Referenced by interpreter::execute().
opEqual()
value opEqual (value & a, value & b)
Definition at line 1172 of file bytecodeEngine.cpp.
References value::getBool(), value::getDeci(), value::getInt(), interpreter::invokeFunc(), value::kind, rex::managePtr(), value::members, valueKindComparator, value::vBool, value::vDeci, and value::vInt.
Referenced by interpreter::execute().
opGreaterEqual()
value opGreaterEqual (value & a, value & b)
Definition at line 1232 of file bytecodeEngine.cpp.
References value::getBool(), value::getDeci(), value::getInt(), interpreter::invokeFunc(), value::kind, rex::managePtr(), value::members, valueKindComparator, value::vBool, value::vDeci, and value::vInt.
Referenced by interpreter::execute().
opGreaterThan()
value opGreaterThan (value & a, value & b)
Definition at line 1292 of file bytecodeEngine.cpp.
References value::getBool(), value::getDeci(), value::getInt(), interpreter::invokeFunc(), value::kind, rex::managePtr(), value::members, valueKindComparator, value::vBool, value::vDeci, and value::vInt.
Referenced by interpreter::execute().
opIncrement()
value opIncrement (const managedPtr< value > & ptr)
Definition at line 1457 of file bytecodeEngine.cpp.
References interpreter::invokeFunc(), value::vDeci, and value::vInt.
Referenced by interpreter::execute().
opIndex()
value opIndex (const managedPtr< value > & ptr, value & a)
Definition at line 1648 of file bytecodeEngine.cpp.
References value::getInt(), value::getStr(), interpreter::invokeFunc(), value::vObject, and value::vVec.
Referenced by interpreter::execute().
opLessEqual()
value opLessEqual (value & a, value & b)
Definition at line 1262 of file bytecodeEngine.cpp.
References value::getBool(), value::getDeci(), value::getInt(), interpreter::invokeFunc(), value::kind, rex::managePtr(), value::members, valueKindComparator, value::vBool, value::vDeci, and value::vInt.
Referenced by interpreter::execute().
opLessThan()
value opLessThan (value & a, value & b)
Definition at line 1322 of file bytecodeEngine.cpp.
References value::getBool(), value::getDeci(), value::getInt(), interpreter::invokeFunc(), value::kind, rex::managePtr(), value::members, valueKindComparator, value::vBool, value::vDeci, and value::vInt.
Referenced by interpreter::execute().
opLogicAnd()
value opLogicAnd (value & a, value & b)
Definition at line 1412 of file bytecodeEngine.cpp.
References value::getBool(), value::getInt(), interpreter::invokeFunc(), value::kind, rex::managePtr(), value::members, valueKindComparator, value::vBool, and value::vInt.
Referenced by interpreter::execute().
opLogicOr()
value opLogicOr (value & a, value & b)
Definition at line 1432 of file bytecodeEngine.cpp.
References value::getBool(), value::getInt(), value::getRef(), interpreter::invokeFunc(), value::isRef(), value::kind, rex::managePtr(), value::members, valueKindComparator, value::vBool, and value::vInt.
Referenced by interpreter::execute().
opMod()
value opMod (value & a, value & b)
Definition at line 1112 of file bytecodeEngine.cpp.
References value::getBool(), value::getInt(), interpreter::invokeFunc(), value::kind, rex::managePtr(), value::members, valueKindComparator, value::vBool, and value::vInt.
Referenced by interpreter::execute().
opModAssign()
value opModAssign (const managedPtr< value > & ptr, value & a)
Definition at line 1632 of file bytecodeEngine.cpp.
References value::getInt(), interpreter::invokeFunc(), value::kind, valueKindComparator, and value::vInt.
Referenced by interpreter::execute().
opMul()
value opMul (value & a, value & b)
Definition at line 1052 of file bytecodeEngine.cpp.
References value::getBool(), value::getDeci(), value::getInt(), interpreter::invokeFunc(), value::kind, rex::managePtr(), value::members, valueKindComparator, value::vBool, value::vDeci, and value::vInt.
Referenced by interpreter::execute().
opMulAssign()
value opMulAssign (const managedPtr< value > & ptr, value & a)
Definition at line 1576 of file bytecodeEngine.cpp.
References value::getDeci(), value::getInt(), interpreter::invokeFunc(), value::kind, valueKindComparator, value::vDeci, and value::vInt.
Referenced by interpreter::execute().
opNegate()
value opNegate (value & a)
Definition at line 1497 of file bytecodeEngine.cpp.
References value::getBool(), value::getDeci(), value::getInt(), interpreter::invokeFunc(), value::kind, rex::managePtr(), value::members, value::vBool, value::vDeci, and value::vInt.
Referenced by interpreter::execute().
opNotEqual()
value opNotEqual (value & a, value & b)
Definition at line 1202 of file bytecodeEngine.cpp.
References value::getBool(), value::getDeci(), value::getInt(), interpreter::invokeFunc(), value::kind, rex::managePtr(), value::members, valueKindComparator, value::vBool, value::vDeci, and value::vInt.
Referenced by interpreter::execute().
opSub()
value opSub (value & a, value & b)
Definition at line 1022 of file bytecodeEngine.cpp.
References value::getBool(), value::getDeci(), value::getInt(), interpreter::invokeFunc(), value::kind, rex::managePtr(), value::members, valueKindComparator, value::vBool, value::vDeci, and value::vInt.
Referenced by interpreter::execute().
opSubAssign()
value opSubAssign (const managedPtr< value > & ptr, value & a)
Definition at line 1548 of file bytecodeEngine.cpp.
References value::getDeci(), value::getInt(), interpreter::invokeFunc(), value::kind, valueKindComparator, value::vDeci, and value::vInt.
Referenced by interpreter::execute().
prepareForFuncInvoke()
void prepareForFuncInvoke (const managedPtr< value > & func, uint64_t argc)
prepare for the function call stack frame
Parameters
func the function body
Definition at line 2263 of file bytecodeEngine.cpp.
References interpreter::callStack, interpreter::evalStack, rex::managePtr(), and interpreter::moduleCxt.
Referenced by interpreter::execute(), and interpreter::invokeFunc().
prepareForLambdaInvoke()
void prepareForLambdaInvoke (const managedPtr< value > & func, uint64_t argc)
Definition at line 2281 of file bytecodeEngine.cpp.
References interpreter::callStack.
Referenced by interpreter::execute(), and interpreter::invokeFunc().
prepareForLambdaMethodInvoke()
void prepareForLambdaMethodInvoke (const managedPtr< value > & func, uint64_t argc)
Definition at line 2290 of file bytecodeEngine.cpp.
References interpreter::callStack.
Referenced by interpreter::execute(), and interpreter::invokeFunc().
prepareForMethodInvoke()
void prepareForMethodInvoke (const managedPtr< value > & func, uint64_t argc)
Definition at line 2271 of file bytecodeEngine.cpp.
References interpreter::callStack, interpreter::evalStack, rex::managePtr(), and interpreter::moduleCxt.
Referenced by interpreter::execute(), and interpreter::invokeFunc().
restoreState()
void restoreState (const state & s)
Definition at line 1738 of file bytecodeEngine.cpp.
References interpreter::callStack, interpreter::state::evalStack, interpreter::evalStack, interpreter::state::frame, interpreter::state::localCxt, and interpreter::state::program.
Referenced by interpreter::interpret().
throwErr()
void throwErr (const value & err) static
throw error in native functions
Note
interpreter will make a wrapper for the exceptions in native functions, and make sure it could be catch by internal exception handler
Warning
DO NOT TRY TO CATCH THE EXCEPTION BY YOURSELF, IT WILL BREAK THE STACK FRAMES.
Parameters
err the error to throw
Definition at line 1686 of file bytecodeEngine.cpp.
Referenced by interpreter::execute(), and rex::nativeFn().
Member Data Documentation
callStack
vec<environment::stackFrame> callStack
Definition at line 209 of file bytecodeEngine.hpp.
Referenced by interpreter::execute(), interpreter::getBacktrace(), interpreter::getBytecodeModule(), interactiveShell(), interpreter::interpret(), interpreter::interpreter(), interpreter::prepareForFuncInvoke(), interpreter::prepareForLambdaInvoke(), interpreter::prepareForLambdaMethodInvoke(), interpreter::prepareForMethodInvoke(), and interpreter::restoreState().
env
managedPtr<environment> env
Definition at line 208 of file bytecodeEngine.hpp.
Referenced by interpreter::execute(), rex::bytecodeEngine::forEachRexModulesPath(), interactiveShell(), rex::nativeFn(), rex::bytecodeEngine::requireModule(), rex::bytecodeEngine::requireNativeModule(), and rex::bytecodeEngine::requirePackage().
evalStack
vec<value> evalStack
Definition at line 212 of file bytecodeEngine.hpp.
Referenced by interpreter::execute(), interactiveShell(), interpreter::interpret(), interpreter::invokeFunc(), interpreter::invokeNativeFn(), interpreter::invokeNativeMethod(), interpreter::prepareForFuncInvoke(), interpreter::prepareForMethodInvoke(), and interpreter::restoreState().
exceptionHandlers
vec<state> exceptionHandlers
Definition at line 213 of file bytecodeEngine.hpp.
Referenced by interpreter::execute(), and interpreter::interpret().
interpreterCxt
value::cxtObject interpreterCxt
Definition at line 210 of file bytecodeEngine.hpp.
Referenced by interpreter::execute(), interactiveShell(), main(), rex::bytecodeEngine::requireModule(), rex::bytecodeEngine::requireNativeModule(), and rex::bytecodeEngine::requirePackage().
moduleCxt
managedPtr<value> moduleCxt
Definition at line 211 of file bytecodeEngine.hpp.
Referenced by interpreter::execute(), interpreter::interpreter(), interpreter::prepareForFuncInvoke(), and interpreter::prepareForMethodInvoke().
The documentation for this class was generated from the following files:
interpreter/bytecodeEngine.hpp
interpreter/bytecodeEngine.cpp