reXscript: exec/main.cpp File Reference
main.cpp File Reference
#include <iostream>
#include "exceptions/parserException.hpp"
#include "exceptions/signalException.hpp"
#include "interpreter/builtInMethods.hpp"
#include "interpreter/bytecodeEngine.hpp"
#include "frontend/parser.hpp"
#include "exceptions/errorInAnotherInterpreter.hpp"
#include <ffi/ffi.hpp>
Functions
void interactiveShell (rex::managedPtr< rex::bytecodeEngine::interpreter > &interpreter)
void loadFile (rex::managedPtr< rex::bytecodeEngine::interpreter > &interpreter, const rex::vstr &path)
void ffiGenerator (const rex::vstr &path)
void disasm (const rex::vstr &path)
void getArgs (const rex::managedPtr< rex::bytecodeEngine::environment > &env, int argc, const char **argv, const char **pos)
int main (int argc, const char **argv)
Variables
const char * helpMsg
Function Documentation
disasm()
void disasm (const rex::vstr & path)
Definition at line 97 of file main.cpp.
References rex::bytecodeEngine::compile(), and rex::wstring2string().
Referenced by main().
ffiGenerator()
void ffiGenerator (const rex::vstr & path)
Definition at line 91 of file main.cpp.
References ffiDescriptor::fromFile(), ffiDescriptor::generateHeader(), and rex::wstring2string().
Referenced by main().
getArgs()
void getArgs (const rex::managedPtr< rex::bytecodeEngine::environment > & env, int argc, const char ** argv, const char ** pos)
Definition at line 108 of file main.cpp.
References rex::stringMethods::getMethodsCxt(), rex::managePtr(), and rex::string2wstring().
Referenced by main().
interactiveShell()
void interactiveShell (rex::managedPtr< rex::bytecodeEngine::interpreter > & interpreter)
Definition at line 18 of file main.cpp.
References codeBuilder::buildStmt(), interpreter::callStack, interpreter::env, interpreter::evalStack, signalException::get(), interpreter::getBacktrace(), rex::stringMethods::getMethodsCxt(), value::getStr(), interpreter::interpret(), interpreter::interpreterCxt, rex::managePtr(), parser::parseStmts(), rex::string2wstring(), interpreterSignal::what(), and rex::wstring2string().
Referenced by main().
loadFile()
void loadFile (rex::managedPtr< rex::bytecodeEngine::interpreter > & interpreter, const rex::vstr & path)
Definition at line 77 of file main.cpp.
References interpreter::getBacktrace(), rex::bytecodeEngine::require(), errorInAnotherInterpreter::what(), and rex::wstring2string().
Referenced by main().
main()
int main (int argc, const char ** argv)
Definition at line 115 of file main.cpp.
References disasm(), ffiGenerator(), getArgs(), rex::bytecodeEngine::getRexEnvironment(), helpMsg, interactiveShell(), interpreter::interpreterCxt, loadFile(), rex::managePtr(), rex::bytecodeEngine::requireWithPath(), rex::bytecodeEngine::rexEnvironmentInstance, and rex::string2wstring().
Variable Documentation
helpMsg
const char* helpMsg
Initial value:
= "Usage: rex [--help] [-m module] [file] args\n"
                      "\n"
                      "Optional arguments: \n"
                      "  -m                execute the specify module \n"
                      "  --generate-ffi\tspecify the FFI config file\n"
                      "  file          \tspecify the file to be executed\n"
                      "  args              the arguments pass to reXscript as `rexArgs`"
Definition at line 10 of file main.cpp.
Referenced by main().