reXscript: rex::bytecodeEngine Namespace Reference
rex::bytecodeEngine Namespace Reference
Classes
struct environment
class codeBuilder
class interpreter
struct bytecodeStruct
struct runtimeSourceFileMsg
struct codeStruct
struct bytecodeModule
Functions
bytecodeModule compile (const vstr &filepath)
compile file
vint spawnThread (const managedPtr< environment > &env, const managedPtr< value > &cxt, const managedPtr< value > &func, const vec< value > &args, const managedPtr< value > &passThisPtr=nullptr)
Spawns a new thread and returns its ID.
void rexThreadWrapper (managedPtr< environment > env, vint tid, managedPtr< value > cxt, managedPtr< value > func, vec< value > args, managedPtr< value > passThisPtr=nullptr)
Wrapper function for starting a new thread. This function is passed as a parameter to std::thread's constructor.
value waitForThread (const managedPtr< environment > &env, vint id)
Waits for the thread with the specified ID to finish execution and returns the result.
managedPtr< value > requireModule (interpreter *in, const vstr &path)
managedPtr< value > requireModuleWithPath (interpreter *in, const vstr &path)
managedPtr< value > requireNativeModule (interpreter *in, const vstr &path)
managedPtr< value > requireNativeModuleWithPath (interpreter *in, const vstr &path)
managedPtr< value > requirePackage (interpreter *in, const vstr &path)
managedPtr< value > requirePackageWithPath (interpreter *in, const vstr &path)
managedPtr< value > requireWithPath (interpreter *in, const vstr &path)
managedPtr< environment > getRexEnvironment ()
managedPtr< value > require (interpreter *in, const vstr &path)
template<typename F >
void forEachRexModulesPath (interpreter *in, F callback)
Variables
managedPtr< environment > rexEnvironmentInstance = managePtr(environment{})
Function Documentation
compile()
bytecodeModule compile (const vstr & filepath)
compile file
Parameters
filepath
Returns
the bytecode module
Definition at line 22 of file bytecodeEngine.cpp.
References codeBuilder::buildStmt(), AST::child, bytecodeModule::codeStructs, bytecodeModule::entryBlock, parser::parseFile(), bytecodeModule::putCodeStruct(), rex::string2wstring(), and rex::wstring2string().
Referenced by disasm(), requireModule(), and requirePackage().
forEachRexModulesPath()
void rex::bytecodeEngine::forEachRexModulesPath (interpreter * in, F callback)
Definition at line 371 of file bytecodeEngine.hpp.
References interpreter::env.
Referenced by requireModuleWithPath(), requireNativeModuleWithPath(), and requirePackageWithPath().
getRexEnvironment()
managedPtr< environment > getRexEnvironment ()
Definition at line 294 of file bytecodeEngine.cpp.
References rex::stringMethods::getMethodsCxt(), rex::vecMethods::getMethodsCxt(), rex::globalMethods::getMethodsCxt(), rex::getRexExecPath(), rex::managePtr(), rex::split(), and rex::string2wstring().
Referenced by main().
require()
managedPtr< value > require (interpreter * in, const vstr & path)
Definition at line 315 of file bytecodeEngine.cpp.
References rex::getDylibSuffix(), requireModule(), requireNativeModule(), requirePackage(), rex::string2wstring(), and rex::wstring2string().
Referenced by loadFile().
requireModule()
managedPtr< value > requireModule (interpreter * in, const vstr & path)
Definition at line 97 of file bytecodeEngine.cpp.
References compile(), interpreter::env, signalException::get(), rex::stringMethods::getMethodsCxt(), interpreter::interpreterCxt, rex::managePtr(), interpreterSignal::what(), and rex::wstring2string().
Referenced by rex::nativeFn(), require(), and requireModuleWithPath().
requireModuleWithPath()
managedPtr< value > requireModuleWithPath (interpreter * in, const vstr & path)
Definition at line 138 of file bytecodeEngine.cpp.
References forEachRexModulesPath(), rex::path::getRealpath(), rex::path::join(), and requireModule().
Referenced by rex::nativeFn(), and requireWithPath().
requireNativeModule()
managedPtr< value > requireNativeModule (interpreter * in, const vstr & path)
Definition at line 158 of file bytecodeEngine.cpp.
References interpreter::env, signalException::get(), rex::stringMethods::getMethodsCxt(), interpreter::interpreterCxt, rex::managePtr(), interpreterSignal::what(), and rex::wstring2string().
Referenced by require(), and requireNativeModuleWithPath().
requireNativeModuleWithPath()
managedPtr< value > requireNativeModuleWithPath (interpreter * in, const vstr & path)
Definition at line 202 of file bytecodeEngine.cpp.
References forEachRexModulesPath(), rex::path::getRealpath(), rex::path::join(), and requireNativeModule().
Referenced by rex::nativeFn(), and requireWithPath().
requirePackage()
managedPtr< value > requirePackage (interpreter * in, const vstr & path)
Definition at line 222 of file bytecodeEngine.cpp.
References compile(), interpreter::env, signalException::get(), rex::stringMethods::getMethodsCxt(), interpreter::interpreterCxt, rex::managePtr(), interpreterSignal::what(), and rex::wstring2string().
Referenced by require(), and requirePackageWithPath().
requirePackageWithPath()
managedPtr< value > requirePackageWithPath (interpreter * in, const vstr & path)
Definition at line 259 of file bytecodeEngine.cpp.
References forEachRexModulesPath(), rex::path::getRealpath(), rex::path::join(), and requirePackage().
Referenced by requireWithPath().
requireWithPath()
managedPtr< value > requireWithPath (interpreter * in, const vstr & path)
Definition at line 279 of file bytecodeEngine.cpp.
References rex::getDylibSuffix(), requireModuleWithPath(), requireNativeModuleWithPath(), requirePackageWithPath(), rex::string2wstring(), and rex::wstring2string().
Referenced by main(), and rex::nativeFn().
rexThreadWrapper()
void rexThreadWrapper (managedPtr< environment > env, vint tid, managedPtr< value > cxt, managedPtr< value > func, vec< value > args, managedPtr< value > passThisPtr = nullptr)
Wrapper function for starting a new thread. This function is passed as a parameter to std::thread's constructor.
Parameters
env The environment in which the new thread will be executed.
tid The ID of the new thread.
cxt The context object in which the new thread will be executed.
func The function object to be called in the new thread.
args The arguments to be passed to the function object.
passThisPtr The object to be passed as the this pointer to the function object.
Definition at line 60 of file bytecodeEngine.cpp.
References signalException::get(), rex::managePtr(), interpreterSignal::what(), and rex::wstring2string().
Referenced by spawnThread().
spawnThread()
vint spawnThread (const managedPtr< environment > & env, const managedPtr< value > & cxt, const managedPtr< value > & func, const vec< value > & args, const managedPtr< value > & passThisPtr = nullptr)
Spawns a new thread and returns its ID.
Parameters
env The environment in which the new thread will be executed.
cxt The context object in which the new thread will be executed.
func The function object to be called in the new thread.
args The arguments to be passed to the function object.
passThisPtr The object to be passed as the this pointer to the function object.
Returns
The ID of the new thread.
Definition at line 52 of file bytecodeEngine.cpp.
References rexThreadWrapper().
Referenced by rex::nativeFn().
waitForThread()
value waitForThread (const managedPtr< environment > & env, vint id)
Waits for the thread with the specified ID to finish execution and returns the result.
Parameters
env The environment in which the thread is being executed.
id The ID of the thread to wait for.
Returns
The result of the thread.
Definition at line 90 of file bytecodeEngine.cpp.
Referenced by rex::nativeFn().
Variable Documentation
rexEnvironmentInstance
managedPtr< environment > rexEnvironmentInstance = managePtr(environment{})
Definition at line 20 of file bytecodeEngine.cpp.
Referenced by dis(), and main().