reXscript: rex::vecMethods Namespace Reference
rex::vecMethods Namespace Reference
Namespaces
iterator
Functions
nativeFn (contains, interpreter, args, passThisPtr)
nativeFn (append, interpreter, args, passThisPtr)
nativeFn (pop, interpreter, args, passThisPtr)
nativeFn (remove, interpreter, args, passThisPtr)
nativeFn (removeAll, interpreter, args, passThisPtr)
nativeFn (rexEqual, interpreter, args, passThisPtr)
nativeFn (rexNotEqual, interpreter, args, passThisPtr)
nativeFn (length, interpreter, args, passThisPtr)
nativeFn (rexIter, interpreter, args, passThisPtr)
value::cxtObject getMethodsCxt ()
Function Documentation
getMethodsCxt()
value::cxtObject getMethodsCxt ()
Definition at line 163 of file builtInMethods.cpp.
References rex::managePtr().
Referenced by rex::globalMethods::getMethodsCxt(), rex::vecMethods::iterator::getMethodsCxt(), rex::hashMapMethods::getMethodsCxt(), rex::getRexEnvironment(), interpreter::interpret(), and rex::nativeFn().
nativeFn() [1/9]
rex::vecMethods::nativeFn (append , interpreter , args , passThisPtr)
nativeFn() [2/9]
rex::vecMethods::nativeFn (contains , interpreter , args , passThisPtr)
nativeFn() [3/9]
rex::vecMethods::nativeFn (length , interpreter , args , passThisPtr)
nativeFn() [4/9]
rex::vecMethods::nativeFn (pop , interpreter , args , passThisPtr)
nativeFn() [5/9]
rex::vecMethods::nativeFn (remove , interpreter , args , passThisPtr)
nativeFn() [6/9]
rex::vecMethods::nativeFn (removeAll , interpreter , args , passThisPtr)
nativeFn() [7/9]
rex::vecMethods::nativeFn (rexEqual , interpreter , args , passThisPtr)
nativeFn() [8/9]
rex::vecMethods::nativeFn (rexIter , interpreter , args , passThisPtr)
nativeFn() [9/9]
rex::vecMethods::nativeFn (rexNotEqual , interpreter , args , passThisPtr)