reXscript: rex::mutexMethods Namespace Reference
rex::mutexMethods Namespace Reference
Functions
value::cxtObject getMethodsCxt (std::mutex *ptr)
nativeFn (rexInit, interpreter, args, passThisPtr)
nativeFn (lock, interpreter, args, passThisPtr)
nativeFn (tryLock, interpreter, args, passThisPtr)
nativeFn (unlock, interpreter, args, passThisPtr)
nativeFn (rexFree, interpreter, args, passThisPtr)
nativeFn (finalize, interpreter, args, passThisPtr)
Function Documentation
getMethodsCxt()
value::cxtObject getMethodsCxt (std::mutex * ptr)
Definition at line 1207 of file builtInMethods.cpp.
References rex::managePtr().
Referenced by rex::globalMethods::getMethodsCxt(), rex::threadingMethods::getThreadingModule(), interpreter::makeIt(), and rex::nativeFn().
nativeFn() [1/6]
nativeFn (finalize , interpreter , args , passThisPtr)
Definition at line 1260 of file builtInMethods.cpp.
nativeFn() [2/6]
nativeFn (lock , interpreter , args , passThisPtr)
Definition at line 1231 of file builtInMethods.cpp.
nativeFn() [3/6]
nativeFn (rexFree , interpreter , args , passThisPtr)
Definition at line 1254 of file builtInMethods.cpp.
nativeFn() [4/6]
nativeFn (rexInit , interpreter , args , passThisPtr)
Definition at line 1219 of file builtInMethods.cpp.
nativeFn() [5/6]
nativeFn (tryLock , interpreter , args , passThisPtr)
Definition at line 1243 of file builtInMethods.cpp.
nativeFn() [6/6]
nativeFn (unlock , interpreter , args , passThisPtr)
Definition at line 1248 of file builtInMethods.cpp.