reXscript: rex::stringMethods Namespace Reference
rex::stringMethods Namespace Reference
Functions
nativeFn (contains, interpreter, args, passThisPtr)
nativeFn (substr, interpreter, args, passThisPtr)
nativeFn (startsWith, interpreter, args, passThisPtr)
nativeFn (endsWith, interpreter, args, passThisPtr)
nativeFn (charAt, interpreter, args, passThisPtr)
nativeFn (fromChar, interpreter, args, passThisPtr)
nativeFn (length, interpreter, args, passThisPtr)
nativeFn (rexEqual, interpreter, args, passThisPtr)
nativeFn (rexNotEqual, interpreter, args, passThisPtr)
nativeFn (rexAdd, interpreter, args, passThisPtr)
nativeFn (rexAddAssign, interpreter, args, passThisPtr)
nativeFn (join, interpreter, args, passThisPtr)
nativeFn (encode, interpreter, args, passThisPtr)
nativeFn (trim, interpreter, args, passThisPtr)
nativeFn (split, interpreter, args, passThisPtr)
value::cxtObject getMethodsCxt ()
Function Documentation
getMethodsCxt()
value::cxtObject getMethodsCxt ()
Definition at line 18 of file builtInMethods.cpp.
References rex::path::join(), rex::managePtr(), and rex::split().
Referenced by getArgs(), rex::getRexEnvironment(), rex::importExternModuleEx(), rex::importExternPackageEx(), rex::importNativeModuleEx(), interactiveShell(), interpreter::interpret(), interpreter::makeErr(), and rex::nativeFn().
nativeFn() [1/15]
rex::stringMethods::nativeFn (charAt , interpreter , args , passThisPtr)
nativeFn() [2/15]
rex::stringMethods::nativeFn (contains , interpreter , args , passThisPtr)
nativeFn() [3/15]
rex::stringMethods::nativeFn (encode , interpreter , args , passThisPtr)
nativeFn() [4/15]
rex::stringMethods::nativeFn (endsWith , interpreter , args , passThisPtr)
nativeFn() [5/15]
rex::stringMethods::nativeFn (fromChar , interpreter , args , passThisPtr)
nativeFn() [6/15]
rex::stringMethods::nativeFn (join , interpreter , args , passThisPtr)
nativeFn() [7/15]
rex::stringMethods::nativeFn (length , interpreter , args , passThisPtr)
nativeFn() [8/15]
rex::stringMethods::nativeFn (rexAdd , interpreter , args , passThisPtr)
nativeFn() [9/15]
rex::stringMethods::nativeFn (rexAddAssign , interpreter , args , passThisPtr)
nativeFn() [10/15]
rex::stringMethods::nativeFn (rexEqual , interpreter , args , passThisPtr)
nativeFn() [11/15]
rex::stringMethods::nativeFn (rexNotEqual , interpreter , args , passThisPtr)
nativeFn() [12/15]
rex::stringMethods::nativeFn (split , interpreter , args , passThisPtr)
nativeFn() [13/15]
rex::stringMethods::nativeFn (startsWith , interpreter , args , passThisPtr)
nativeFn() [14/15]
rex::stringMethods::nativeFn (substr , interpreter , args , passThisPtr)
nativeFn() [15/15]
rex::stringMethods::nativeFn (trim , interpreter , args , passThisPtr)