reXscript: rex::hashMapMethods::iterator Namespace Reference
rex::hashMapMethods::iterator Namespace Reference
Functions
nativeFn (next, interpreter, args, passThisPtr)
value::cxtObject getMethodsCxt (value::linkedListObject &container)
Function Documentation
getMethodsCxt()
value::cxtObject getMethodsCxt (value::linkedListObject & container)
Definition at line 867 of file builtInMethods.cpp.
References value::getLinkedList(), rex::linkedListMethods::getMethodsCxt(), and rex::managePtr().
nativeFn()
rex::hashMapMethods::iterator::nativeFn (next , interpreter , args , passThisPtr)