reXscript: rex::linkedListMethods Namespace Reference
rex::linkedListMethods Namespace Reference
Namespaces
iterator
Functions
nativeFn (contains, interpreter, args, passThisPtr)
nativeFn (append, interpreter, args, passThisPtr)
nativeFn (pop, interpreter, args, passThisPtr)
nativeFn (remove, interpreter, args, passThisPtr)
nativeFn (removeAll, interpreter, args, passThisPtr)
nativeFn (rexIter, interpreter, args, passThisPtr)
value::cxtObject getMethodsCxt ()
Function Documentation
getMethodsCxt()
value::cxtObject getMethodsCxt ()
Definition at line 726 of file builtInMethods.cpp.
References rex::managePtr().
Referenced by rex::linkedListMethods::iterator::getMethodsCxt(), rex::hashMapMethods::iterator::getMethodsCxt(), rex::hashMapMethods::keysIterator::getMethodsCxt(), rex::hashMapMethods::getMethodsCxt(), and rex::nativeFn().
nativeFn() [1/6]
rex::linkedListMethods::nativeFn (append , interpreter , args , passThisPtr)
nativeFn() [2/6]
rex::linkedListMethods::nativeFn (contains , interpreter , args , passThisPtr)
nativeFn() [3/6]
rex::linkedListMethods::nativeFn (pop , interpreter , args , passThisPtr)
nativeFn() [4/6]
rex::linkedListMethods::nativeFn (remove , interpreter , args , passThisPtr)
nativeFn() [5/6]
rex::linkedListMethods::nativeFn (removeAll , interpreter , args , passThisPtr)
nativeFn() [6/6]
rex::linkedListMethods::nativeFn (rexIter , interpreter , args , passThisPtr)