reXscript: rex::threadingMethods Namespace Reference
rex::threadingMethods Namespace Reference
Functions
nativeFn (start, interpreter, args, passThisPtr)
nativeFn (wait, interpreter, args, passThisPtr)
nativeFn (sleep, interpreter, args, passThisPtr)
value::cxtObject getMethodsCxt ()
value getThreadingModule ()
Function Documentation
getMethodsCxt()
value::cxtObject getMethodsCxt ()
Definition at line 597 of file builtInMethods.cpp.
References rex::managePtr().
getThreadingModule()
value getThreadingModule ()
Definition at line 606 of file builtInMethods.cpp.
References rex::mutexMethods::getMethodsCxt().
Referenced by rex::globalMethods::getMethodsCxt().
nativeFn() [1/3]
rex::threadingMethods::nativeFn (sleep , interpreter , args , passThisPtr)
nativeFn() [2/3]
rex::threadingMethods::nativeFn (start , interpreter , args , passThisPtr)
nativeFn() [3/3]
rex::threadingMethods::nativeFn (wait , interpreter , args , passThisPtr)