reXscript: rex Namespace Reference
rex Namespace Reference
Namespaces
bytesMethods
ffi
globalMethods
hashMapMethods
iterMethods
linkedListMethods
mutexMethods
objectMethods
path
stringMethods
threadingMethods
vecMethods
Classes
class AST
class lexer
class parser
struct formatterTagInfo
struct environment
class interpreter
The interpreter class for reXscript.
class value
class endOfFileException
class errorInAnotherInterpreter
class importError
class interpreterSignal
class parserException
class rexException
class signalBreak
class signalContinue
class signalException
class signalReturn
class unexpectedTokenException
Typedefs
using vsize = unsigned long long
using vint = int64_t
using vbool = bool
using vdeci = double
using vstr = std::wstring
using vchar = wchar_t
using vbytes = std::string
using vbyte = char
template<typename T >
using vec = std::vector< T >
template<typename A , typename B >
using map = std::map< A, B >
template<typename T >
using unsafePtr = T *
template<typename T >
using managedPtr = std::shared_ptr< T >
using unknownPtr = unsafePtr< void * >
Functions
nativeFn (stringMethods::contains, interpreter, args, passThisPtr)
nativeFn (stringMethods::substr, interpreter, args, passThisPtr)
nativeFn (stringMethods::trim, interpreter, args, passThisPtr)
nativeFn (stringMethods::split, interpreter, args, passThisPtr)
nativeFn (stringMethods::startsWith, interpreter, args, passThisPtr)
nativeFn (stringMethods::endsWith, interpreter, args, passThisPtr)
nativeFn (stringMethods::charAt, interpreter, args, passThisPtr)
nativeFn (stringMethods::fromChar, interpreter, args, passThisPtr)
nativeFn (stringMethods::length, interpreter, args, passThisPtr)
nativeFn (stringMethods::rexEqual, interpreter, args, passThisPtr)
nativeFn (stringMethods::rexNotEqual, interpreter, args, passThisPtr)
nativeFn (stringMethods::rexAdd, interpreter, args, passThisPtr)
nativeFn (stringMethods::rexAddAssign, interpreter, args, passThisPtr)
nativeFn (stringMethods::join, interpreter, args, passThisPtr)
nativeFn (stringMethods::encode, interpreter, args, passThisPtr)
nativeFn (vecMethods::length, interpreter, args, passThisPtr)
nativeFn (vecMethods::contains, interpreter, args, passThisPtr)
nativeFn (vecMethods::append, interpreter, args, passThisPtr)
nativeFn (vecMethods::pop, interpreter, args, passThisPtr)
nativeFn (vecMethods::empty, interpreter, args, passThisPtr)
nativeFn (vecMethods::remove, interpreter, args, passThisPtr)
nativeFn (vecMethods::removeAll, interpreter, args, passThisPtr)
nativeFn (vecMethods::rexEqual, interpreter, args, passThisPtr)
nativeFn (vecMethods::rexNotEqual, interpreter, args, passThisPtr)
nativeFn (vecMethods::rexIter, interpreter, args, passThisPtr)
nativeFn (globalMethods::rexDeci, interpreter, args, passThisPtr)
nativeFn (globalMethods::rexInt, interpreter, args, passThisPtr)
nativeFn (globalMethods::input, interpreter, args, passThisPtr)
nativeFn (globalMethods::stringify, interpreter, args, passThisPtr)
nativeFn (globalMethods::print, interpreter, args, passThisPtr)
nativeFn (globalMethods::hash, interpreter, args, passThisPtr)
nativeFn (globalMethods::type, interpreter, args, passThisPtr)
nativeFn (globalMethods::charsetsMethods::ansiEncoder, interpreter, args, passThisPtr)
nativeFn (globalMethods::charsetsMethods::ansiDecoder, interpreter, args, passThisPtr)
nativeFn (globalMethods::charsetsMethods::utf8Encoder, interpreter, args, passThisPtr)
nativeFn (globalMethods::charsetsMethods::utf8Decoder, interpreter, args, passThisPtr)
nativeFn (globalMethods::rexRequireMod, interpreter, args, passThisPtr)
nativeFn (globalMethods::mutex, interpreter, args, passThisPtr)
nativeFn (globalMethods::rexRequireNativeMod, interpreter, args, passThisPtr)
nativeFn (globalMethods::rexRequirePackage, interpreter, args, passThisPtr)
nativeFn (globalMethods::rexRequire, interpreter, args, passThisPtr)
nativeFn (globalMethods::format, interpreter, args, passThisPtr)
nativeFn (threadingMethods::start, interpreter, args, passThisPtr)
nativeFn (threadingMethods::wait, interpreter, args, passThisPtr)
nativeFn (threadingMethods::sleep, interpreter, args, passThisPtr)
nativeFn (bytesMethods::contains, interpreter, args, passThisPtr)
nativeFn (bytesMethods::slice, interpreter, args, passThisPtr)
nativeFn (bytesMethods::length, interpreter, args, passThisPtr)
nativeFn (bytesMethods::rexEqual, interpreter, args, passThisPtr)
nativeFn (bytesMethods::rexNotEqual, interpreter, args, passThisPtr)
nativeFn (bytesMethods::concat, interpreter, args, passThisPtr)
nativeFn (bytesMethods::decode, interpreter, args, passThisPtr)
nativeFn (vecMethods::iterator::next, interpreter, args, passThisPtr)
nativeFn (linkedListMethods::contains, interpreter, args, passThisPtr)
nativeFn (linkedListMethods::append, interpreter, args, passThisPtr)
nativeFn (linkedListMethods::pop, interpreter, args, passThisPtr)
nativeFn (linkedListMethods::popFront, interpreter, args, passThisPtr)
nativeFn (linkedListMethods::pushFront, interpreter, args, passThisPtr)
nativeFn (linkedListMethods::front, interpreter, args, passThisPtr)
nativeFn (linkedListMethods::back, interpreter, args, passThisPtr)
nativeFn (linkedListMethods::empty, interpreter, args, passThisPtr)
nativeFn (linkedListMethods::length, interpreter, args, passThisPtr)
nativeFn (linkedListMethods::remove, interpreter, args, passThisPtr)
nativeFn (linkedListMethods::removeAll, interpreter, args, passThisPtr)
nativeFn (linkedListMethods::rexIter, interpreter, args, passThisPtr)
nativeFn (linkedListMethods::iterator::next, interpreter, args, passThisPtr)
nativeFn (globalMethods::linkedList, interpreter, args, passThisPtr)
nativeFn (hashMapMethods::toObject, interpreter, args, passThisPtr)
nativeFn (hashMapMethods::fromObject, interpreter, args, passThisPtr)
nativeFn (hashMapMethods::rexStr, interpreter, args, passThisPtr)
nativeFn (hashMapMethods::insert, interpreter, args, passThisPtr)
nativeFn (hashMapMethods::realloc, interpreter, args, passThisPtr)
nativeFn (hashMapMethods::remove, interpreter, args, passThisPtr)
nativeFn (hashMapMethods::rexIndex, interpreter, args, passThisPtr)
nativeFn (hashMapMethods::contains, interpreter, args, passThisPtr)
nativeFn (hashMapMethods::rexIter, interpreter, args, passThisPtr)
nativeFn (hashMapMethods::iterator::next, interpreter, args, passThisPtr)
nativeFn (hashMapMethods::keys, interpreter, args, passThisPtr)
nativeFn (hashMapMethods::keysIterator::next, interpreter, args, passThisPtr)
nativeFn (hashMapMethods::rexClone, interpreter, args, passThisPtr)
nativeFn (globalMethods::hashMap, interpreter, args, passThisPtr)
nativeFn (iterMethods::collect, interpreter, args, passThisPtr)
nativeFn (iterMethods::forEach, interpreter, args, passThisPtr)
nativeFn (objectMethods::iterate, interpreter, args, passThisPtr)
nativeFn (objectMethods::addAttr, interpreter, args, passThisPtr)
nativeFn (objectMethods::removeAttr, interpreter, args, passThisPtr)
nativeFn (objectMethods::contains, interpreter, args, passThisPtr)
vint spawnThread (const managedPtr< environment > &env, const managedPtr< value > &cxt, const managedPtr< value > &func, const vec< value > &args, const managedPtr< value > &passThisPtr=nullptr)
Spawns a new thread and returns its ID.
void rexThreadWrapper (managedPtr< environment > env, vint tid, managedPtr< value > cxt, managedPtr< value > func, vec< value > args, managedPtr< value > passThisPtr=nullptr)
Wrapper function for starting a new thread. This function is passed as a parameter to std::thread's constructor.
value waitForThread (const managedPtr< environment > &env, vint id)
Waits for the thread with the specified ID to finish execution and returns the result.
void getSelfRef (value &r)
std::string wstring2string (const std::wstring &str)
std::wstring string2wstring (const std::string &str)
std::wstring string2wstring (const std::wstring &str)
std::wstring buildErrorMessage (vsize line, vsize col, const vstr &what)
template<typename T >
managedPtr< T > managePtr (const T &v)
void parseString (std::wistream &input, vstr &value)
template<typename T >
void split (const std::basic_string< T > &s, const std::basic_string< T > &delim, std::vector< std::basic_string< T >> &ret)
template<typename T , typename cbT >
void split (const std::basic_string< T > &s, const std::basic_string< T > &delim, cbT callback)
template<typename T >
std::basic_string< T > replaceAll (std::basic_string< T > src, const std::basic_string< T > &oldValue, const std::basic_string< T > &newValue)
vstr getOSName ()
vstr getCPUArch ()
vstr getDylibSuffix ()
vbytes getPrintableBytes (const vbytes &src)
vbytes getRexExecPath ()
rex::managedPtr< rex::environment > getRexEnvironment ()
Get the environment object for the current reXscript interpreter.
managedPtr< value > importExternModule (interpreter *interpreter, const vstr &path)
Import an external reXscript module.
managedPtr< value > importNativeModule (interpreter *interpreter, const vstr &path)
Import a native module.
managedPtr< value > importExternPackage (interpreter *interpreter, const vstr &pkgName)
Import an external reXscript package.
managedPtr< value > importExternModuleEx (interpreter *interpreter, const vstr &fullPath)
Import an external reXscript module without importPathPrefix.
managedPtr< value > importNativeModuleEx (interpreter *interpreter, const vstr &fullPath)
Import a native module without importPathPrefix.
managedPtr< value > importExternPackageEx (interpreter *interpreter, const vstr &pkgDirPath)
Import an external package without importPathPrefix.
managedPtr< value > importEx (interpreter *interpreter, const vstr &modPath)
AST getFileAST (const vstr &path)
rex::managedPtr< rex::interpreter > getRexInterpreter ()
void atExitHandler ()
void initializeAtExitHandler ()
void atExitWrapper (int sig)
void initialize ()
Variables
managedPtr< environment > rexEnvironmentInstance
managedPtr< interpreter > rexInterpreterInstance
Typedef Documentation
managedPtr
using managedPtr = std::shared_ptr<T>
Definition at line 71 of file share.hpp.
map
using map = std::map<A, B>
Definition at line 57 of file share.hpp.
unknownPtr
using unknownPtr = unsafePtr<void *>
Definition at line 73 of file share.hpp.
unsafePtr
using unsafePtr = T *
Definition at line 68 of file share.hpp.
vbool
using vbool = bool
Definition at line 48 of file share.hpp.
vbyte
using vbyte = char
Definition at line 53 of file share.hpp.
vbytes
using vbytes = std::string
Definition at line 52 of file share.hpp.
vchar
using vchar = wchar_t
Definition at line 51 of file share.hpp.
vdeci
using vdeci = double
Definition at line 49 of file share.hpp.
vec
using vec = std::vector<T>
Definition at line 55 of file share.hpp.
vint
using vint = int64_t
Definition at line 47 of file share.hpp.
vsize
using vsize = unsigned long long
Definition at line 46 of file share.hpp.
vstr
using vstr = std::wstring
Definition at line 50 of file share.hpp.
Function Documentation
atExitHandler()
void atExitHandler ()
Definition at line 292 of file rex.cpp.
References signalException::get(), rexEnvironmentInstance, rexInterpreterInstance, interpreterSignal::what(), and wstring2string().
Referenced by atExitWrapper(), and main().
atExitWrapper()
void atExitWrapper (int sig)
Definition at line 321 of file rex.cpp.
References atExitHandler().
Referenced by initializeAtExitHandler().
buildErrorMessage()
std::wstring buildErrorMessage (rex::vsize line, rex::vsize col, const vstr & what)
Definition at line 24 of file share.cpp.
getCPUArch()
rex::vstr getCPUArch ()
Definition at line 86 of file share.cpp.
References architecture.
Referenced by rex::globalMethods::getMethodsCxt().
getDylibSuffix()
rex::vstr getDylibSuffix ()
Definition at line 90 of file share.cpp.
References dylibSuffix.
Referenced by rex::globalMethods::getMethodsCxt(), and importEx().
getFileAST()
AST getFileAST (const vstr & path)
Definition at line 264 of file rex.cpp.
References parser::parseFile(), string2wstring(), and wstring2string().
Referenced by importExternModuleEx(), and importExternPackageEx().
getOSName()
rex::vstr getOSName ()
Definition at line 82 of file share.cpp.
References operatingSystem.
Referenced by rex::globalMethods::getMethodsCxt().
getPrintableBytes()
rex::vbytes getPrintableBytes (const vbytes & src)
Definition at line 94 of file share.cpp.
Referenced by value::operator vstr().
getRexEnvironment()
rex::managedPtr< rex::environment > getRexEnvironment ()
Get the environment object for the current reXscript interpreter.
Returns
A pointer to the environment object
Definition at line 16 of file rex.cpp.
References rex::stringMethods::getMethodsCxt(), rex::vecMethods::getMethodsCxt(), rex::globalMethods::getMethodsCxt(), managePtr(), split(), and string2wstring().
Referenced by initialize().
getRexExecPath()
rex::vbytes getRexExecPath ()
Definition at line 106 of file share.cpp.
Referenced by rex::globalMethods::getMethodsCxt().
getRexInterpreter()
rex::managedPtr< rex::interpreter > getRexInterpreter ()
Definition at line 284 of file rex.cpp.
References managePtr(), and rexEnvironmentInstance.
Referenced by initialize().
getSelfRef()
void getSelfRef (value & r)
Definition at line 362 of file value.cpp.
References value::refObj.
Referenced by interpreter::interpret(), interpreter::interpretAssignments(), nativeFn(), interpreter::opAdd(), interpreter::opBinaryAnd(), interpreter::opBinaryOr(), interpreter::opBinaryShiftLeft(), interpreter::opBinaryShiftRight(), interpreter::opBinaryXor(), interpreter::opDiv(), interpreter::opEqual(), interpreter::opGreaterEqual(), interpreter::opGreaterThan(), interpreter::opLessEqual(), interpreter::opLessThan(), interpreter::opLogicAnd(), interpreter::opLogicOr(), interpreter::opMod(), interpreter::opMul(), interpreter::opNotEqual(), and interpreter::opSub().
importEx()
managedPtr< value > importEx (interpreter * interpreter, const vstr & modPath)
Definition at line 238 of file rex.cpp.
References interpreter::env, getDylibSuffix(), importExternModule(), importExternPackage(), importNativeModule(), interpreter::interpreterCxt, managePtr(), interpreter::moduleCxt, string2wstring(), and wstring2string().
Referenced by loadFile(), main(), and nativeFn().
importExternModule()
managedPtr< value > importExternModule (interpreter * interpreter, const vstr & path)
Import an external reXscript module.
Parameters
interpreter The environment object for the current interpreter
path The path to the module file to import
Returns
A pointer to the module context object
Definition at line 32 of file rex.cpp.
References eleGetRef, interpreter::env, rex::path::getRealpath(), importExternModuleEx(), rex::path::join(), and interpreter::makeErr().
Referenced by importEx(), and nativeFn().
importExternModuleEx()
managedPtr< value > importExternModuleEx (interpreter * interpreter, const vstr & fullPath)
Import an external reXscript module without importPathPrefix.
Parameters
interpreter The interpreter
path The path to the module file to import
Returns
A pointer to the module context object
Definition at line 111 of file rex.cpp.
References AST::child, interpreter::env, interpreter::getBacktrace(), getFileAST(), rex::stringMethods::getMethodsCxt(), interpreter::interpret(), interpreter::invokeFunc(), managePtr(), interpreter::moduleCxt, importError::what(), and wstring2string().
Referenced by importExternModule().
importExternPackage()
managedPtr< value > importExternPackage (interpreter * interpreter, const vstr & pkgName)
Import an external reXscript package.
Parameters
interpreter The interpreter
path The path to the package directory to import
Returns
A pointer to the module context object
Definition at line 85 of file rex.cpp.
References eleGetRef, interpreter::env, rex::path::getRealpath(), importExternPackageEx(), rex::path::join(), and interpreter::makeErr().
Referenced by importEx(), and nativeFn().
importExternPackageEx()
managedPtr< value > importExternPackageEx (interpreter * interpreter, const vstr & pkgDirPath)
Import an external package without importPathPrefix.
Parameters
interpreter The interpreter
pkgDirPath The path to the package file to import
Returns
A pointer to the package context object
Definition at line 195 of file rex.cpp.
References AST::child, interpreter::env, interpreter::getBacktrace(), getFileAST(), rex::stringMethods::getMethodsCxt(), interpreter::interpret(), interpreter::invokeFunc(), managePtr(), interpreter::moduleCxt, importError::what(), and wstring2string().
Referenced by importExternPackage().
importNativeModule()
managedPtr< value > importNativeModule (interpreter * interpreter, const vstr & path)
Import a native module.
Parameters
interpreter The interpreter
path The path to the native module file to import
Returns
A pointer to the module context object
Definition at line 58 of file rex.cpp.
References eleGetRef, interpreter::env, rex::path::getRealpath(), importNativeModuleEx(), rex::path::join(), and interpreter::makeErr().
Referenced by importEx(), and nativeFn().
importNativeModuleEx()
managedPtr< value > importNativeModuleEx (interpreter * interpreter, const vstr & fullPath)
Import a native module without importPathPrefix.
Parameters
interpreter The interpreter
path The path to the native module file to import
Returns
A pointer to the module context object
Definition at line 152 of file rex.cpp.
References interpreter::env, signalException::get(), interpreter::getBacktrace(), rex::stringMethods::getMethodsCxt(), managePtr(), interpreter::moduleCxt, interpreterSignal::what(), and wstring2string().
Referenced by importNativeModule().
initialize()
void initialize ()
Definition at line 326 of file rex.cpp.
References getRexEnvironment(), getRexInterpreter(), initializeAtExitHandler(), rexEnvironmentInstance, and rexInterpreterInstance.
Referenced by main().
initializeAtExitHandler()
void initializeAtExitHandler ()
Definition at line 316 of file rex.cpp.
References atExitWrapper().
Referenced by initialize().
managePtr()
managedPtr<T> rex::managePtr (const T & v)
Definition at line 76 of file share.hpp.
Referenced by value::deepCopy(), getArgs(), rex::stringMethods::getMethodsCxt(), rex::vecMethods::getMethodsCxt(), rex::bytesMethods::getMethodsCxt(), rex::linkedListMethods::getMethodsCxt(), rex::globalMethods::getMethodsCxt(), rex::threadingMethods::getMethodsCxt(), rex::iterMethods::getMethodsCxt(), rex::objectMethods::getMethodsCxt(), rex::vecMethods::iterator::getMethodsCxt(), rex::mutexMethods::getMethodsCxt(), rex::linkedListMethods::iterator::getMethodsCxt(), rex::hashMapMethods::iterator::getMethodsCxt(), rex::hashMapMethods::keysIterator::getMethodsCxt(), rex::hashMapMethods::getMethodsCxt(), getRexEnvironment(), getRexInterpreter(), importEx(), importExternModuleEx(), importExternPackageEx(), importNativeModuleEx(), interactiveShell(), interpreter::interpret(), interpreter::invokeFunc(), interpreter::makeErr(), interpreter::makeIt(), nativeFn(), interpreter::opAdd(), interpreter::opBinaryAnd(), interpreter::opBinaryOr(), interpreter::opBinaryShiftLeft(), interpreter::opBinaryShiftRight(), interpreter::opBinaryXor(), interpreter::opDiv(), interpreter::opEqual(), value::operator[](), interpreter::opGreaterEqual(), interpreter::opGreaterThan(), interpreter::opLessEqual(), interpreter::opLessThan(), interpreter::opLogicAnd(), interpreter::opLogicOr(), interpreter::opMod(), interpreter::opMul(), interpreter::opNotEqual(), interpreter::opSub(), and rexThreadWrapper().
nativeFn() [1/87]
rex::nativeFn (bytesMethods::concat , interpreter , args , passThisPtr)
Definition at line 701 of file builtInMethods.cpp.
nativeFn() [2/87]
rex::nativeFn (bytesMethods::contains , interpreter , args , passThisPtr)
Definition at line 670 of file builtInMethods.cpp.
References eleGetRef.
nativeFn() [3/87]
rex::nativeFn (bytesMethods::decode , interpreter , args , passThisPtr)
Definition at line 709 of file builtInMethods.cpp.
References eleGetRef.
nativeFn() [4/87]
rex::nativeFn (bytesMethods::length , interpreter , args , passThisPtr)
Definition at line 683 of file builtInMethods.cpp.
nativeFn() [5/87]
rex::nativeFn (bytesMethods::rexEqual , interpreter , args , passThisPtr)
Definition at line 687 of file builtInMethods.cpp.
nativeFn() [6/87]
rex::nativeFn (bytesMethods::rexNotEqual , interpreter , args , passThisPtr)
Definition at line 694 of file builtInMethods.cpp.
nativeFn() [7/87]
rex::nativeFn (bytesMethods::slice , interpreter , args , passThisPtr)
Definition at line 678 of file builtInMethods.cpp.
References eleGetRef, and rex::bytesMethods::getMethodsCxt().
nativeFn() [8/87]
rex::nativeFn (globalMethods::charsetsMethods::ansiDecoder , interpreter , args , passThisPtr)
Definition at line 439 of file builtInMethods.cpp.
References eleGetRef, and rex::mutexMethods::getMethodsCxt().
nativeFn() [9/87]
rex::nativeFn (globalMethods::charsetsMethods::ansiEncoder , interpreter , args , passThisPtr)
Definition at line 428 of file builtInMethods.cpp.
References eleGetRef, and rex::mutexMethods::getMethodsCxt().
nativeFn() [10/87]
rex::nativeFn (globalMethods::charsetsMethods::utf8Decoder , interpreter , args , passThisPtr)
Definition at line 457 of file builtInMethods.cpp.
References eleGetRef, rex::mutexMethods::getMethodsCxt(), and string2wstring().
nativeFn() [11/87]
rex::nativeFn (globalMethods::charsetsMethods::utf8Encoder , interpreter , args , passThisPtr)
Definition at line 450 of file builtInMethods.cpp.
References eleGetRef, rex::mutexMethods::getMethodsCxt(), and wstring2string().
nativeFn() [12/87]
rex::nativeFn (globalMethods::format , interpreter , args , passThisPtr)
Definition at line 510 of file builtInMethods.cpp.
References formatterTagInfo::base, rex::stringMethods::getMethodsCxt(), getSelfRef(), formatterTagInfo::kind, formatterTagInfo::parse(), and formatterTagInfo::precision.
nativeFn() [13/87]
rex::nativeFn (globalMethods::hash , interpreter , args , passThisPtr)
Definition at line 349 of file builtInMethods.cpp.
References eleGetRef, value::getBool(), value::getBytes(), value::getDeci(), value::getInt(), value::getStr(), value::kind, managePtr(), and value::members.
nativeFn() [14/87]
rex::nativeFn (globalMethods::hashMap , interpreter , args , passThisPtr)
Definition at line 1084 of file builtInMethods.cpp.
References rex::hashMapMethods::getMethodsCxt().
nativeFn() [15/87]
rex::nativeFn (globalMethods::input , interpreter , args , passThisPtr)
Definition at line 301 of file builtInMethods.cpp.
References rex::stringMethods::getMethodsCxt(), and string2wstring().
nativeFn() [16/87]
rex::nativeFn (globalMethods::linkedList , interpreter , args , passThisPtr)
Definition at line 864 of file builtInMethods.cpp.
References rex::linkedListMethods::getMethodsCxt(), and managePtr().
nativeFn() [17/87]
rex::nativeFn (globalMethods::mutex , interpreter , args , passThisPtr)
Definition at line 477 of file builtInMethods.cpp.
References rex::mutexMethods::getMethodsCxt().
nativeFn() [18/87]
rex::nativeFn (globalMethods::print , interpreter , args , passThisPtr)
Definition at line 319 of file builtInMethods.cpp.
References eleGetRef, eleRefObj, and wstring2string().
nativeFn() [19/87]
rex::nativeFn (globalMethods::rexDeci , interpreter , args , passThisPtr)
Definition at line 268 of file builtInMethods.cpp.
References eleGetRef, value::getBool(), value::getInt(), value::getStr(), and value::kind.
nativeFn() [20/87]
rex::nativeFn (globalMethods::rexInt , interpreter , args , passThisPtr)
Definition at line 284 of file builtInMethods.cpp.
References eleGetRef, value::getBool(), value::getDeci(), value::getStr(), and value::kind.
nativeFn() [21/87]
rex::nativeFn (globalMethods::rexRequire , interpreter , args , passThisPtr)
Definition at line 502 of file builtInMethods.cpp.
References importEx().
nativeFn() [22/87]
rex::nativeFn (globalMethods::rexRequireMod , interpreter , args , passThisPtr)
Definition at line 464 of file builtInMethods.cpp.
References importExternModule().
nativeFn() [23/87]
rex::nativeFn (globalMethods::rexRequireNativeMod , interpreter , args , passThisPtr)
Definition at line 481 of file builtInMethods.cpp.
References importNativeModule().
nativeFn() [24/87]
rex::nativeFn (globalMethods::rexRequirePackage , interpreter , args , passThisPtr)
Definition at line 494 of file builtInMethods.cpp.
References importExternPackage().
nativeFn() [25/87]
rex::nativeFn (globalMethods::stringify , interpreter , args , passThisPtr)
Definition at line 307 of file builtInMethods.cpp.
References eleGetRef, rex::mutexMethods::getMethodsCxt(), value::getStr(), and managePtr().
nativeFn() [26/87]
rex::nativeFn (globalMethods::type , interpreter , args , passThisPtr)
Definition at line 372 of file builtInMethods.cpp.
References rex::mutexMethods::getMethodsCxt().
nativeFn() [27/87]
rex::nativeFn (hashMapMethods::contains , interpreter , args , passThisPtr)
Definition at line 1006 of file builtInMethods.cpp.
References eleGetRef.
nativeFn() [28/87]
rex::nativeFn (hashMapMethods::fromObject , interpreter , args , passThisPtr)
Definition at line 911 of file builtInMethods.cpp.
References eleGetRef, rex::stringMethods::getMethodsCxt(), and value::members.
nativeFn() [29/87]
rex::nativeFn (hashMapMethods::insert , interpreter , args , passThisPtr)
Definition at line 933 of file builtInMethods.cpp.
References eleGetRef, rex::vecMethods::getMethodsCxt(), rex::linkedListMethods::getMethodsCxt(), and managePtr().
nativeFn() [30/87]
rex::nativeFn (hashMapMethods::iterator::next , interpreter , args , passThisPtr)
Definition at line 1036 of file builtInMethods.cpp.
References interpreter::makeIt().
nativeFn() [31/87]
rex::nativeFn (hashMapMethods::keys , interpreter , args , passThisPtr)
Definition at line 1048 of file builtInMethods.cpp.
References rex::vecMethods::getMethodsCxt().
nativeFn() [32/87]
rex::nativeFn (hashMapMethods::keysIterator::next , interpreter , args , passThisPtr)
Definition at line 1065 of file builtInMethods.cpp.
nativeFn() [33/87]
rex::nativeFn (hashMapMethods::realloc , interpreter , args , passThisPtr)
Definition at line 953 of file builtInMethods.cpp.
References rex::linkedListMethods::getMethodsCxt(), and managePtr().
nativeFn() [34/87]
rex::nativeFn (hashMapMethods::remove , interpreter , args , passThisPtr)
Definition at line 972 of file builtInMethods.cpp.
References eleGetRef.
nativeFn() [35/87]
rex::nativeFn (hashMapMethods::rexClone , interpreter , args , passThisPtr)
Definition at line 1077 of file builtInMethods.cpp.
References managePtr().
nativeFn() [36/87]
rex::nativeFn (hashMapMethods::rexIndex , interpreter , args , passThisPtr)
Definition at line 989 of file builtInMethods.cpp.
References eleGetRef, and interpreter::makeErr().
nativeFn() [37/87]
rex::nativeFn (hashMapMethods::rexIter , interpreter , args , passThisPtr)
Definition at line 1023 of file builtInMethods.cpp.
References rex::mutexMethods::getMethodsCxt().
nativeFn() [38/87]
rex::nativeFn (hashMapMethods::rexStr , interpreter , args , passThisPtr)
Definition at line 919 of file builtInMethods.cpp.
References rex::stringMethods::getMethodsCxt().
nativeFn() [39/87]
rex::nativeFn (hashMapMethods::toObject , interpreter , args , passThisPtr)
Definition at line 897 of file builtInMethods.cpp.
References eleGetRef, eleRefObj, value::getStr(), value::kind, interpreter::makeErr(), and value::vStr.
nativeFn() [40/87]
rex::nativeFn (iterMethods::collect , interpreter , args , passThisPtr)
Definition at line 1095 of file builtInMethods.cpp.
References rex::vecMethods::getMethodsCxt(), interpreter::makeErr(), and managePtr().
nativeFn() [41/87]
rex::nativeFn (iterMethods::forEach , interpreter , args , passThisPtr)
Definition at line 1133 of file builtInMethods.cpp.
References rex::vecMethods::getMethodsCxt(), interpreter::makeErr(), and managePtr().
nativeFn() [42/87]
rex::nativeFn (linkedListMethods::append , interpreter , args , passThisPtr)
Definition at line 776 of file builtInMethods.cpp.
References eleRefObj.
nativeFn() [43/87]
rex::nativeFn (linkedListMethods::back , interpreter , args , passThisPtr)
Definition at line 800 of file builtInMethods.cpp.
nativeFn() [44/87]
rex::nativeFn (linkedListMethods::contains , interpreter , args , passThisPtr)
Definition at line 765 of file builtInMethods.cpp.
References eleGetRef.
nativeFn() [45/87]
rex::nativeFn (linkedListMethods::empty , interpreter , args , passThisPtr)
Definition at line 804 of file builtInMethods.cpp.
nativeFn() [46/87]
rex::nativeFn (linkedListMethods::front , interpreter , args , passThisPtr)
Definition at line 796 of file builtInMethods.cpp.
nativeFn() [47/87]
rex::nativeFn (linkedListMethods::iterator::next , interpreter , args , passThisPtr)
Definition at line 852 of file builtInMethods.cpp.
References interpreter::makeIt().
nativeFn() [48/87]
rex::nativeFn (linkedListMethods::length , interpreter , args , passThisPtr)
Definition at line 808 of file builtInMethods.cpp.
nativeFn() [49/87]
rex::nativeFn (linkedListMethods::pop , interpreter , args , passThisPtr)
Definition at line 781 of file builtInMethods.cpp.
nativeFn() [50/87]
rex::nativeFn (linkedListMethods::popFront , interpreter , args , passThisPtr)
Definition at line 786 of file builtInMethods.cpp.
nativeFn() [51/87]
rex::nativeFn (linkedListMethods::pushFront , interpreter , args , passThisPtr)
Definition at line 791 of file builtInMethods.cpp.
References eleRefObj.
nativeFn() [52/87]
rex::nativeFn (linkedListMethods::remove , interpreter , args , passThisPtr)
Definition at line 812 of file builtInMethods.cpp.
References eleGetRef.
nativeFn() [53/87]
rex::nativeFn (linkedListMethods::removeAll , interpreter , args , passThisPtr)
Definition at line 827 of file builtInMethods.cpp.
References eleGetRef.
nativeFn() [54/87]
rex::nativeFn (linkedListMethods::rexIter , interpreter , args , passThisPtr)
Definition at line 840 of file builtInMethods.cpp.
References rex::mutexMethods::getMethodsCxt().
nativeFn() [55/87]
rex::nativeFn (objectMethods::addAttr , interpreter , args , passThisPtr)
Definition at line 1183 of file builtInMethods.cpp.
References eleGetRef, and eleRefObj.
nativeFn() [56/87]
rex::nativeFn (objectMethods::contains , interpreter , args , passThisPtr)
Definition at line 1193 of file builtInMethods.cpp.
References eleGetRef.
nativeFn() [57/87]
rex::nativeFn (objectMethods::iterate , interpreter , args , passThisPtr)
Definition at line 1174 of file builtInMethods.cpp.
References rex::stringMethods::getMethodsCxt(), and managePtr().
nativeFn() [58/87]
rex::nativeFn (objectMethods::removeAttr , interpreter , args , passThisPtr)
Definition at line 1188 of file builtInMethods.cpp.
References eleGetRef.
nativeFn() [59/87]
rex::nativeFn (stringMethods::charAt , interpreter , args , passThisPtr)
Definition at line 96 of file builtInMethods.cpp.
nativeFn() [60/87]
rex::nativeFn (stringMethods::contains , interpreter , args , passThisPtr)
Definition at line 38 of file builtInMethods.cpp.
References eleGetRef.
nativeFn() [61/87]
rex::nativeFn (stringMethods::encode , interpreter , args , passThisPtr)
Definition at line 156 of file builtInMethods.cpp.
References eleGetRef.
nativeFn() [62/87]
rex::nativeFn (stringMethods::endsWith , interpreter , args , passThisPtr)
Definition at line 90 of file builtInMethods.cpp.
nativeFn() [63/87]
rex::nativeFn (stringMethods::fromChar , interpreter , args , passThisPtr)
Definition at line 100 of file builtInMethods.cpp.
nativeFn() [64/87]
rex::nativeFn (stringMethods::join , interpreter , args , passThisPtr)
Definition at line 139 of file builtInMethods.cpp.
References rex::mutexMethods::getMethodsCxt(), getSelfRef(), and value::getStr().
nativeFn() [65/87]
rex::nativeFn (stringMethods::length , interpreter , args , passThisPtr)
Definition at line 105 of file builtInMethods.cpp.
nativeFn() [66/87]
rex::nativeFn (stringMethods::rexAdd , interpreter , args , passThisPtr)
Definition at line 123 of file builtInMethods.cpp.
References rex::mutexMethods::getMethodsCxt().
nativeFn() [67/87]
rex::nativeFn (stringMethods::rexAddAssign , interpreter , args , passThisPtr)
Definition at line 130 of file builtInMethods.cpp.
nativeFn() [68/87]
rex::nativeFn (stringMethods::rexEqual , interpreter , args , passThisPtr)
Definition at line 109 of file builtInMethods.cpp.
nativeFn() [69/87]
rex::nativeFn (stringMethods::rexNotEqual , interpreter , args , passThisPtr)
Definition at line 116 of file builtInMethods.cpp.
nativeFn() [70/87]
rex::nativeFn (stringMethods::split , interpreter , args , passThisPtr)
Definition at line 74 of file builtInMethods.cpp.
References rex::vecMethods::getMethodsCxt(), and split().
nativeFn() [71/87]
rex::nativeFn (stringMethods::startsWith , interpreter , args , passThisPtr)
Definition at line 84 of file builtInMethods.cpp.
nativeFn() [72/87]
rex::nativeFn (stringMethods::substr , interpreter , args , passThisPtr)
Definition at line 46 of file builtInMethods.cpp.
References rex::mutexMethods::getMethodsCxt(), and interpreter::makeErr().
nativeFn() [73/87]
rex::nativeFn (stringMethods::trim , interpreter , args , passThisPtr)
Definition at line 67 of file builtInMethods.cpp.
References rex::mutexMethods::getMethodsCxt().
nativeFn() [74/87]
rex::nativeFn (threadingMethods::sleep , interpreter , args , passThisPtr)
Definition at line 651 of file builtInMethods.cpp.
nativeFn() [75/87]
rex::nativeFn (threadingMethods::start , interpreter , args , passThisPtr)
Definition at line 635 of file builtInMethods.cpp.
References value::deepCopy(), managePtr(), and spawnThread().
nativeFn() [76/87]
rex::nativeFn (threadingMethods::wait , interpreter , args , passThisPtr)
Definition at line 646 of file builtInMethods.cpp.
References waitForThread().
nativeFn() [77/87]
rex::nativeFn (vecMethods::append , interpreter , args , passThisPtr)
Definition at line 193 of file builtInMethods.cpp.
References eleGetRef, and managePtr().
nativeFn() [78/87]
rex::nativeFn (vecMethods::contains , interpreter , args , passThisPtr)
Definition at line 182 of file builtInMethods.cpp.
References eleGetRef.
nativeFn() [79/87]
rex::nativeFn (vecMethods::empty , interpreter , args , passThisPtr)
Definition at line 204 of file builtInMethods.cpp.
nativeFn() [80/87]
rex::nativeFn (vecMethods::iterator::next , interpreter , args , passThisPtr)
Definition at line 737 of file builtInMethods.cpp.
References value::isRef(), and interpreter::makeIt().
nativeFn() [81/87]
rex::nativeFn (vecMethods::length , interpreter , args , passThisPtr)
Definition at line 178 of file builtInMethods.cpp.
nativeFn() [82/87]
rex::nativeFn (vecMethods::pop , interpreter , args , passThisPtr)
Definition at line 199 of file builtInMethods.cpp.
nativeFn() [83/87]
rex::nativeFn (vecMethods::remove , interpreter , args , passThisPtr)
Definition at line 208 of file builtInMethods.cpp.
References eleGetRef.
nativeFn() [84/87]
rex::nativeFn (vecMethods::removeAll , interpreter , args , passThisPtr)
Definition at line 223 of file builtInMethods.cpp.
References eleGetRef.
nativeFn() [85/87]
rex::nativeFn (vecMethods::rexEqual , interpreter , args , passThisPtr)
Definition at line 236 of file builtInMethods.cpp.
nativeFn() [86/87]
rex::nativeFn (vecMethods::rexIter , interpreter , args , passThisPtr)
Definition at line 264 of file builtInMethods.cpp.
References rex::mutexMethods::getMethodsCxt().
nativeFn() [87/87]
rex::nativeFn (vecMethods::rexNotEqual , interpreter , args , passThisPtr)
Definition at line 250 of file builtInMethods.cpp.
parseString()
void parseString (std::wistream & input, rex::vstr & value)
Definition at line 30 of file share.cpp.
Referenced by lexer::strStart().
replaceAll()
std::basic_string<T> rex::replaceAll (std::basic_string< T > src, const std::basic_string< T > & oldValue, const std::basic_string< T > & newValue)
Definition at line 125 of file share.hpp.
Referenced by ffiDescriptor::generateHeader().
rexThreadWrapper()
void rexThreadWrapper (managedPtr< environment > env, vint tid, managedPtr< value > cxt, managedPtr< value > func, vec< value > args, managedPtr< value > passThisPtr = nullptr)
Wrapper function for starting a new thread. This function is passed as a parameter to std::thread's constructor.
Parameters
env The environment in which the new thread will be executed.
tid The ID of the new thread.
cxt The context object in which the new thread will be executed.
func The function object to be called in the new thread.
args The arguments to be passed to the function object.
passThisPtr The object to be passed as the this pointer to the function object.
Definition at line 1499 of file interpreter.cpp.
References signalException::get(), managePtr(), interpreterSignal::what(), and wstring2string().
Referenced by spawnThread().
spawnThread()
vint spawnThread (const managedPtr< environment > & env, const managedPtr< value > & cxt, const managedPtr< value > & func, const vec< value > & args, const managedPtr< value > & passThisPtr = nullptr)
Spawns a new thread and returns its ID.
Parameters
env The environment in which the new thread will be executed.
cxt The context object in which the new thread will be executed.
func The function object to be called in the new thread.
args The arguments to be passed to the function object.
passThisPtr The object to be passed as the this pointer to the function object.
Returns
The ID of the new thread.
Definition at line 1488 of file interpreter.cpp.
References rexThreadWrapper().
Referenced by nativeFn().
split() [1/2]
void rex::split (const std::basic_string< T > & s, const std::basic_string< T > & delim, cbT callback)
Definition at line 109 of file share.hpp.
split() [2/2]
void rex::split (const std::basic_string< T > & s, const std::basic_string< T > & delim, std::vector< std::basic_string< T >> & ret)
Definition at line 94 of file share.hpp.
Referenced by ffiDescriptor::fromFile(), rex::stringMethods::getMethodsCxt(), getRexEnvironment(), and nativeFn().
string2wstring() [1/2]
std::wstring string2wstring (const std::string & str)
Definition at line 14 of file share.cpp.
References utf8Unicode::utf8ToUnicode().
Referenced by ffiDescriptor::fromFile(), getArgs(), getFileAST(), rex::globalMethods::getMethodsCxt(), rex::path::getRealpath(), getRexEnvironment(), importEx(), interactiveShell(), main(), nativeFn(), and value::operator vstr().
string2wstring() [2/2]
std::wstring string2wstring (const std::wstring & str)
Definition at line 20 of file share.cpp.
waitForThread()
value waitForThread (const managedPtr< environment > & env, vint id)
Waits for the thread with the specified ID to finish execution and returns the result.
Parameters
env The environment in which the thread is being executed.
id The ID of the thread to wait for.
Returns
The result of the thread.
Definition at line 1524 of file interpreter.cpp.
Referenced by nativeFn().
wstring2string()
std::string wstring2string (const std::wstring & str)
Definition at line 8 of file share.cpp.
References utf8Unicode::unicodeToUtf8().
Referenced by atExitHandler(), ffiGenerator(), ffiDescriptor::fromFile(), getFileAST(), rex::path::getRealpath(), importEx(), importExternModuleEx(), importExternPackageEx(), importNativeModuleEx(), interactiveShell(), loadFile(), main(), nativeFn(), and rexThreadWrapper().
Variable Documentation
rexEnvironmentInstance
managedPtr< environment > rexEnvironmentInstance
Definition at line 19 of file interpreter.cpp.
Referenced by atExitHandler(), getRexInterpreter(), initialize(), and main().
rexInterpreterInstance
managedPtr< interpreter > rexInterpreterInstance
Definition at line 20 of file interpreter.cpp.
Referenced by atExitHandler(), initialize(), and main().