reXscript: rex::path Namespace Reference
rex::path Namespace Reference
Functions
void join (vstr &a, const vstr &b)
vstr getRealpath (const vstr &path)
Variables
constexpr vchar sep = '/'
Function Documentation
getRealpath()
rex::vstr getRealpath (const vstr & path)
Definition at line 137 of file share.cpp.
References rex::string2wstring(), and rex::wstring2string().
Referenced by rex::importExternModule(), rex::importExternPackage(), rex::importNativeModule(), rex::bytecodeEngine::requireModuleWithPath(), rex::bytecodeEngine::requireNativeModuleWithPath(), and rex::bytecodeEngine::requirePackageWithPath().
join()
void join (rex::vstr & a, const vstr & b)
Definition at line 117 of file share.cpp.
References sep.
Referenced by rex::stringMethods::getMethodsCxt(), rex::importExternModule(), rex::importExternPackage(), rex::importNativeModule(), rex::bytecodeEngine::requireModuleWithPath(), rex::bytecodeEngine::requireNativeModuleWithPath(), and rex::bytecodeEngine::requirePackageWithPath().
Variable Documentation
sep
constexpr vchar sep = '/' constexpr
Definition at line 86 of file share.hpp.
Referenced by join().