reXscript: rex::hashMapMethods Namespace Reference
rex::hashMapMethods Namespace Reference
Namespaces
iterator
Functions
nativeFn (insert, interpreter, args, passThisPtr)
nativeFn (realloc, interpreter, args, passThisPtr)
nativeFn (remove, interpreter, args, passThisPtr)
nativeFn (rexIndex, interpreter, args, passThisPtr)
nativeFn (keys, interpreter, args, passThisPtr)
nativeFn (rexIter, interpreter, args, passThisPtr)
nativeFn (rexClone, interpreter, args, passThisPtr)
nativeFn (rexStr, interpreter, args, passThisPtr)
value::cxtObject getMethodsCxt (vint defaultHashTSize=256)
Function Documentation
getMethodsCxt()
value::cxtObject getMethodsCxt (vint defaultHashTSize = 256)
Definition at line 756 of file builtInMethods.cpp.
References rex::vecMethods::getMethodsCxt(), rex::linkedListMethods::getMethodsCxt(), and rex::managePtr().
Referenced by rex::nativeFn().
nativeFn() [1/8]
rex::hashMapMethods::nativeFn (insert , interpreter , args , passThisPtr)
nativeFn() [2/8]
rex::hashMapMethods::nativeFn (keys , interpreter , args , passThisPtr)
nativeFn() [3/8]
rex::hashMapMethods::nativeFn (realloc , interpreter , args , passThisPtr)
nativeFn() [4/8]
rex::hashMapMethods::nativeFn (remove , interpreter , args , passThisPtr)
nativeFn() [5/8]
rex::hashMapMethods::nativeFn (rexClone , interpreter , args , passThisPtr)
nativeFn() [6/8]
rex::hashMapMethods::nativeFn (rexIndex , interpreter , args , passThisPtr)
nativeFn() [7/8]
rex::hashMapMethods::nativeFn (rexIter , interpreter , args , passThisPtr)
nativeFn() [8/8]
rex::hashMapMethods::nativeFn (rexStr , interpreter , args , passThisPtr)