reXscript: rex::globalMethods Namespace Reference
rex::globalMethods Namespace Reference
Namespaces
charsetsMethods
Functions
nativeFn (rexInt, interpreter, args, passThisPtr)
nativeFn (rexDeci, interpreter, args, passThisPtr)
nativeFn (input, interpreter, args, passThisPtr)
nativeFn (print, interpreter, args, passThisPtr)
nativeFn (stringify, interpreter, args, passThisPtr)
nativeFn (rexRequireMod, interpreter, args, passThisPtr)
nativeFn (rexRequireNativeMod, interpreter, args, passThisPtr)
nativeFn (rexRequirePackage, interpreter, args, passThisPtr)
nativeFn (rexRequire, interpreter, args, passThisPtr)
nativeFn (format, interpreter, args, passThisPtr)
nativeFn (hash, interpreter, args, passThisPtr)
nativeFn (linkedList, interpreter, args, passThisPtr)
nativeFn (hashMap, interpreter, args, passThisPtr)
nativeFn (type, interpreter, args, passThisPtr)
nativeFn (mutex, interpreter, args, passThisPtr)
value::cxtObject getMethodsCxt ()
Function Documentation
getMethodsCxt()
value::cxtObject getMethodsCxt ()
Definition at line 371 of file builtInMethods.cpp.
References rex::getCPUArch(), rex::getDylibSuffix(), rex::vecMethods::getMethodsCxt(), rex::mutexMethods::getMethodsCxt(), rex::getOSName(), rex::getRexExecPath(), rex::threadingMethods::getThreadingModule(), rex::managePtr(), and rex::string2wstring().
Referenced by rex::getRexEnvironment().
nativeFn() [1/15]
rex::globalMethods::nativeFn (format , interpreter , args , passThisPtr)
nativeFn() [2/15]
rex::globalMethods::nativeFn (hash , interpreter , args , passThisPtr)
nativeFn() [3/15]
rex::globalMethods::nativeFn (hashMap , interpreter , args , passThisPtr)
nativeFn() [4/15]
rex::globalMethods::nativeFn (input , interpreter , args , passThisPtr)
nativeFn() [5/15]
rex::globalMethods::nativeFn (linkedList , interpreter , args , passThisPtr)
nativeFn() [6/15]
rex::globalMethods::nativeFn (mutex , interpreter , args , passThisPtr)
nativeFn() [7/15]
rex::globalMethods::nativeFn (print , interpreter , args , passThisPtr)
nativeFn() [8/15]
rex::globalMethods::nativeFn (rexDeci , interpreter , args , passThisPtr)
nativeFn() [9/15]
rex::globalMethods::nativeFn (rexInt , interpreter , args , passThisPtr)
nativeFn() [10/15]
rex::globalMethods::nativeFn (rexRequire , interpreter , args , passThisPtr)
nativeFn() [11/15]
rex::globalMethods::nativeFn (rexRequireMod , interpreter , args , passThisPtr)
nativeFn() [12/15]
rex::globalMethods::nativeFn (rexRequireNativeMod , interpreter , args , passThisPtr)
nativeFn() [13/15]
rex::globalMethods::nativeFn (rexRequirePackage , interpreter , args , passThisPtr)
nativeFn() [14/15]
rex::globalMethods::nativeFn (stringify , interpreter , args , passThisPtr)
nativeFn() [15/15]
rex::globalMethods::nativeFn (type , interpreter , args , passThisPtr)