reXscript: ffiDescriptor Struct Reference
ffiDescriptor Struct Reference
#include <ffi.hpp>
Classes
struct ffiConsts
struct ffiExport
struct ffiType
Public Member Functions
void fromFile (const vstr &path)
vstr generateHeader ()
Public Attributes
vstr lib
map< vstr, ffiType > ffiTypes
map< vstr, ffiExport > ffiExports
map< vstr, ffiConsts > ffiConsts
vstr helpers
Detailed Description
Definition at line 11 of file ffi.hpp.
Member Function Documentation
fromFile()
void fromFile (const vstr & path)
Definition at line 8 of file ffi.cpp.
References ffiDescriptor::ffiExports, ffiDescriptor::ffiTypes, ffiDescriptor::helpers, ffiDescriptor::lib, ffiDescriptor::ffiConsts::name, rex::split(), rex::string2wstring(), ffiDescriptor::ffiConsts::type, ffiDescriptor::ffiConsts::value, and rex::wstring2string().
Referenced by ffiGenerator().
generateHeader()
vstr generateHeader ()
Definition at line 125 of file ffi.cpp.
References ffiDescriptor::ffiExports, ffiDescriptor::ffiTypes, ffiDescriptor::helpers, ffiDescriptor::lib, and rex::replaceAll().
Referenced by ffiGenerator().
Member Data Documentation
ffiConsts
map<vstr, ffiConsts> ffiConsts
Definition at line 34 of file ffi.hpp.
ffiExports
map<vstr, ffiExport> ffiExports
Definition at line 32 of file ffi.hpp.
Referenced by ffiDescriptor::fromFile(), and ffiDescriptor::generateHeader().
ffiTypes
map<vstr, ffiType> ffiTypes
Definition at line 30 of file ffi.hpp.
Referenced by ffiDescriptor::fromFile(), and ffiDescriptor::generateHeader().
helpers
vstr helpers
Definition at line 36 of file ffi.hpp.
Referenced by ffiDescriptor::fromFile(), and ffiDescriptor::generateHeader().
lib
vstr lib
Definition at line 28 of file ffi.hpp.
Referenced by ffiDescriptor::fromFile(), and ffiDescriptor::generateHeader().
The documentation for this struct was generated from the following files:
ffi/ffi.hpp
ffi/ffi.cpp