reXscript: exec/test.cpp File Reference
test.cpp File Reference
#include <iostream>
#include <frontend/parser.hpp>
#include <interpreter/bytecodeStructs.hpp>
#include <interpreter/bytecodeEngine.hpp>
#include <interpreter/builtInMethods.hpp>
Functions
void dis ()
int main ()
Function Documentation
dis()
void dis ()
Definition at line 12 of file test.cpp.
References codeBuilder::buildStmt(), rex::globalMethods::getMethodsCxt(), rex::managePtr(), rex::bytecodeEngine::rexEnvironmentInstance, rex::string2wstring(), and rex::wstring2string().
Referenced by main().
main()
int main ()
Definition at line 45 of file test.cpp.
References dis().